package sre

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// ThreadSafetyContract records a struct's concurrency model and synchronization invariants.
type ThreadSafetyContract struct {
	StructName  string   `json:"struct_name"`
	Package     string   `json:"package"`
	SourcePath  string   `json:"source_path"`
	Line        int      `json:"line"`
	LockType    string   `json:"lock_type"`    // Mutex, RWMutex, None
	GuardedVars []string `json:"guarded_vars"` // Fields guarded by lock
	Channels    []string `json:"channels"`     // Associated channels
	Goroutines  int      `json:"goroutines"`   // Spawned go-routines count
}

// GenerateConcurrencyContracts scans for concurrent primitives and generates
// docs/concurrency.md outlining lock contracts and thread-safety invariants.
func GenerateConcurrencyContracts(repoRoot string) (string, error) {
	contracts, err := scanConcurrencyContracts(repoRoot)
	if err != nil {
		return "", err
	}

	sort.Slice(contracts, func(i, j int) bool {
		if contracts[i].Package == contracts[j].Package {
			return contracts[i].StructName < contracts[j].StructName
		}
		return contracts[i].Package < contracts[j].Package
	})

	var sb strings.Builder
	sb.WriteString("# Concurrency, Threading & Lock Contention Reference\n\n")
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 32).\n")
	sb.WriteString("> Documents thread-safety contracts, mutex guards, and synchronization invariants across all subsystems.\n\n")

	sb.WriteString("| Struct / Resource | Package | Synchronization Primitive | Guarded Fields / Invariants | Channel Concurrency | Source |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- | :--- | :--- |\n")

	for _, c := range contracts {
		guarded := "Stateless / Immutable"
		if len(c.GuardedVars) > 0 {
			guarded = strings.Join(c.GuardedVars, ", ")
		}

		chans := "None"
		if len(c.Channels) > 0 {
			chans = strings.Join(c.Channels, ", ")
		}

		sb.WriteString(fmt.Sprintf("| **`%s`** | `%s` | `%s` | %s | %s | [%s:%d](%s#L%d) |\n",
			c.StructName, c.Package, c.LockType, guarded, chans, filepath.Base(c.SourcePath), c.Line, c.SourcePath, c.Line))
	}

	outPath := filepath.Join(repoRoot, "docs", "concurrency.md")
	result := sb.String()
	_, err = storage.AtomicWriteFile(outPath, []byte(result))
	return result, err
}

func scanConcurrencyContracts(repoRoot string) ([]ThreadSafetyContract, error) {
	var contracts []ThreadSafetyContract
	fset := token.NewFileSet()

	err := filepath.WalkDir(repoRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == ".glassmarble" || name == "vendor" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		relPath, _ := filepath.Rel(repoRoot, path)
		relPath = filepath.ToSlash(relPath)

		node, parseErr := parser.ParseFile(fset, path, nil, 0)
		if parseErr != nil {
			return nil
		}

		for _, decl := range node.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}

				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				lockType := "None"
				var guarded []string
				var channels []string

				for _, field := range structType.Fields.List {
					typeStr := exprToString(field.Type)
					if strings.Contains(typeStr, "sync.Mutex") {
						lockType = "sync.Mutex"
					} else if strings.Contains(typeStr, "sync.RWMutex") {
						lockType = "sync.RWMutex"
					} else if strings.HasPrefix(typeStr, "chan ") {
						for _, name := range field.Names {
							channels = append(channels, fmt.Sprintf("`%s` (%s)", name.Name, typeStr))
						}
					} else {
						for _, name := range field.Names {
							if lockType != "None" {
								guarded = append(guarded, fmt.Sprintf("`%s`", name.Name))
							}
						}
					}
				}

				if lockType != "None" || len(channels) > 0 {
					pos := fset.Position(typeSpec.Pos())
					contracts = append(contracts, ThreadSafetyContract{
						StructName:  typeSpec.Name.Name,
						Package:     node.Name.Name,
						SourcePath:  relPath,
						Line:        pos.Line,
						LockType:    lockType,
						GuardedVars: guarded,
						Channels:    channels,
					})
				}
			}
		}
		return nil
	})

	return contracts, err
}

func exprToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return exprToString(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + exprToString(t.X)
	case *ast.ChanType:
		return "chan " + exprToString(t.Value)
	default:
		return "interface{}"
	}
}
