package sre

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// SentinelErrorFact records an extracted sentinel error from the codebase.
type SentinelErrorFact struct {
	Name        string   `json:"name"`
	Package     string   `json:"package"`
	SourcePath  string   `json:"source_path"`
	Line        int      `json:"line"`
	Message     string   `json:"message"`
	DocComment  string   `json:"doc_comment"`
	TriageSteps []string `json:"triage_steps"`
}

// GenerateErrorCatalog scans the repository for sentinel errors and generates
// docs/errors.md with triage playbooks for each error.
func GenerateErrorCatalog(repoRoot string) (string, error) {
	errors, err := scanSentinelErrors(repoRoot)
	if err != nil {
		return "", err
	}

	sort.Slice(errors, func(i, j int) bool {
		if errors[i].Package == errors[j].Package {
			return errors[i].Name < errors[j].Name
		}
		return errors[i].Package < errors[j].Package
	})

	var sb strings.Builder
	sb.WriteString("# Living Error Code Catalog & SRE Triage Playbook\n\n")
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 33).\n")
	sb.WriteString("> Maintains real-time operational runbook entries for all sentinel errors in the codebase.\n\n")

	sb.WriteString("| Error Sentinel | Package | Error Message | Trigger Condition & Triage Playbook | Origin |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- | :--- |\n")

	for _, e := range errors {
		triage := e.DocComment
		if triage == "" {
			triage = "Inspect input parameters and operational logs around trigger site."
		}
		if len(e.TriageSteps) > 0 {
			triage += "<br>• " + strings.Join(e.TriageSteps, "<br>• ")
		}

		triage = strings.ReplaceAll(triage, "|", "\\|")
		triage = strings.ReplaceAll(triage, "\n", " ")

		sb.WriteString(fmt.Sprintf("| **`%s`** | `%s` | *\"%s\"* | %s | [%s:%d](%s#L%d) |\n",
			e.Name, e.Package, e.Message, triage, filepath.Base(e.SourcePath), e.Line, e.SourcePath, e.Line))
	}

	outPath := filepath.Join(repoRoot, "docs", "errors.md")
	result := sb.String()
	_, err = storage.AtomicWriteFile(outPath, []byte(result))
	return result, err
}

func scanSentinelErrors(repoRoot string) ([]SentinelErrorFact, error) {
	var results []SentinelErrorFact
	fset := token.NewFileSet()

	err := filepath.WalkDir(repoRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == ".glassmarble" || name == "vendor" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		relPath, _ := filepath.Rel(repoRoot, path)
		relPath = filepath.ToSlash(relPath)

		node, parseErr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if parseErr != nil {
			return nil
		}

		for _, decl := range node.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.VAR {
				continue
			}

			docText := strings.TrimSpace(genDecl.Doc.Text())
			for _, spec := range genDecl.Specs {
				valSpec, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}

				for i, name := range valSpec.Names {
					if !strings.HasPrefix(name.Name, "Err") {
						continue
					}

					msg := ""
					if i < len(valSpec.Values) {
						if call, ok := valSpec.Values[i].(*ast.CallExpr); ok {
							if len(call.Args) > 0 {
								if lit, ok := call.Args[0].(*ast.BasicLit); ok {
									msg = strings.Trim(lit.Value, `"`)
								}
							}
						}
					}

					pos := fset.Position(name.Pos())
					comment := docText
					if comment == "" && valSpec.Doc != nil {
						comment = strings.TrimSpace(valSpec.Doc.Text())
					}

					var triage []string
					if strings.Contains(strings.ToLower(name.Name), "timeout") {
						triage = append(triage, "Check upstream service health and network latency.")
						triage = append(triage, "Review timeout threshold configuration.")
					} else if strings.Contains(strings.ToLower(name.Name), "notfound") {
						triage = append(triage, "Verify resource identifier exists in storage.")
					} else if strings.Contains(strings.ToLower(name.Name), "auth") || strings.Contains(strings.ToLower(name.Name), "permission") {
						triage = append(triage, "Verify credentials and caller authorization tokens.")
					}

					results = append(results, SentinelErrorFact{
						Name:        name.Name,
						Package:     node.Name.Name,
						SourcePath:  relPath,
						Line:        pos.Line,
						Message:     msg,
						DocComment:  comment,
						TriageSteps: triage,
					})
				}
			}
		}
		return nil
	})

	return results, err
}
