package sre

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Syamchand123/GlassMarble/internal/akg"
	"github.com/Syamchand123/GlassMarble/internal/code_analysis_engine/link"
	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// SentinelErrorFact records an extracted sentinel error from the codebase.
type SentinelErrorFact struct {
	Name        string   `json:"name"`
	Package     string   `json:"package"`
	SourcePath  string   `json:"source_path"`
	Line        int      `json:"line"`
	Message     string   `json:"message"`
	DocComment  string   `json:"doc_comment"`
	TriageSteps []string `json:"triage_steps"`
	// Callers lists up to 5 repo-relative "file#line" entries that reference
	// this sentinel outside its declaration file (Pillar 33: callers from CPG edges,
	// approximated here via parser-identified ast.Ident references).
	Callers []string `json:"callers,omitempty"`
}

// GenerateErrorCatalog scans the repository for sentinel errors and generates
// docs/errors.md with triage playbooks for each error.
func GenerateErrorCatalog(repoRoot string) (string, error) {
	return GenerateErrorCatalogWithGraph(repoRoot, nil)
}

// GenerateErrorCatalogWithGraph is the CPG-aware error catalog: sentinel
// extraction is unchanged (go/parser), but caller resolution prefers the
// CodePropertyGraph — graph.GetInboundEdges per sentinel node, file#line via
// the source node's FileSpec — and falls back to the parser ident-scan when
// graph is nil. A nil graph therefore reproduces GenerateErrorCatalog
// exactly; a non-nil graph is authoritative for the sentinels it knows
// (unknown sentinels keep empty caller lists rather than mixing sources).
func GenerateErrorCatalogWithGraph(repoRoot string, graph *akg.CodePropertyGraph) (string, error) {
	errors, err := scanSentinelErrorsWithGraph(repoRoot, graph)
	if err != nil {
		return "", err
	}

	sort.Slice(errors, func(i, j int) bool {
		if errors[i].Package == errors[j].Package {
			return errors[i].Name < errors[j].Name
		}
		return errors[i].Package < errors[j].Package
	})

	var sb strings.Builder
	sb.WriteString("# Living Error Code Catalog & SRE Triage Playbook\n\n")
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 33).\n")
	sb.WriteString("> Maintains real-time operational runbook entries for all sentinel errors in the codebase.\n\n")

	sb.WriteString("| Error Sentinel | Package | Error Message | Trigger Condition & Triage Playbook | Origin | Callers |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- | :--- | :--- |\n")

	for _, e := range errors {
		triage := e.DocComment
		if triage == "" {
			triage = "Inspect input parameters and operational logs around trigger site."
		}
		if len(e.TriageSteps) > 0 {
			triage += "<br>• " + strings.Join(e.TriageSteps, "<br>• ")
		}

		triage = strings.ReplaceAll(triage, "|", "\\|")
		triage = strings.ReplaceAll(triage, "\n", " ")

		callers := "-"
		if len(e.Callers) > 0 {
			callers = strings.Join(e.Callers, "<br>")
		}

		sb.WriteString(fmt.Sprintf("| **`%s`** | `%s` | *\"%s\"* | %s | [%s:%d](%s#L%d) | %s |\n",
			e.Name, e.Package, e.Message, triage, filepath.Base(e.SourcePath), e.Line, e.SourcePath, e.Line, callers))
	}

	outPath := filepath.Join(repoRoot, "docs", "errors.md")
	result := sb.String()
	_, err = storage.AtomicWriteFile(outPath, []byte(result))
	return result, err
}

func scanSentinelErrors(repoRoot string) ([]SentinelErrorFact, error) {
	return scanSentinelErrorsWithGraph(repoRoot, nil)
}

func scanSentinelErrorsWithGraph(repoRoot string, graph *akg.CodePropertyGraph) ([]SentinelErrorFact, error) {
	var results []SentinelErrorFact
	fset := token.NewFileSet()

	// parsedFiles caches every parsed Go file so caller resolution below
	// reuses the ASTs without a second parse pass.
	type parsedFile struct {
		relPath string
		node    *ast.File
	}
	var parsed []parsedFile

	err := filepath.WalkDir(repoRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == ".glassmarble" || name == "vendor" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		relPath, _ := filepath.Rel(repoRoot, path)
		relPath = filepath.ToSlash(relPath)

		node, parseErr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if parseErr != nil {
			return nil
		}

		parsed = append(parsed, parsedFile{relPath: relPath, node: node})

		for _, decl := range node.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.VAR {
				continue
			}

			docText := strings.TrimSpace(genDecl.Doc.Text())
			for _, spec := range genDecl.Specs {
				valSpec, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}

				for i, name := range valSpec.Names {
					if !strings.HasPrefix(name.Name, "Err") {
						continue
					}

					msg := ""
					if i < len(valSpec.Values) {
						if call, ok := valSpec.Values[i].(*ast.CallExpr); ok {
							if len(call.Args) > 0 {
								if lit, ok := call.Args[0].(*ast.BasicLit); ok {
									msg = strings.Trim(lit.Value, `"`)
								}
							}
						}
					}

					pos := fset.Position(name.Pos())
					comment := docText
					if comment == "" && valSpec.Doc != nil {
						comment = strings.TrimSpace(valSpec.Doc.Text())
					}

					var triage []string
					if strings.Contains(strings.ToLower(name.Name), "timeout") {
						triage = append(triage, "Check upstream service health and network latency.")
						triage = append(triage, "Review timeout threshold configuration.")
					} else if strings.Contains(strings.ToLower(name.Name), "notfound") {
						triage = append(triage, "Verify resource identifier exists in storage.")
					} else if strings.Contains(strings.ToLower(name.Name), "auth") || strings.Contains(strings.ToLower(name.Name), "permission") {
						triage = append(triage, "Verify credentials and caller authorization tokens.")
					}

					results = append(results, SentinelErrorFact{
						Name:        name.Name,
						Package:     node.Name.Name,
						SourcePath:  relPath,
						Line:        pos.Line,
						Message:     msg,
						DocComment:  comment,
						TriageSteps: triage,
					})
				}
			}
		}
		return nil
	})

	if err != nil {
		return results, err
	}

	// Caller resolution: CPG edges when a graph is provided, otherwise the
	// parser ident-scan below. Up to 5 callers (file#line) per error.
	if graph != nil {
		resolveCallersFromGraph(graph, results)
		return results, err
	}
	declFile := make(map[string]string, len(results))
	for _, r := range results {
		if _, ok := declFile[r.Name]; !ok {
			declFile[r.Name] = r.SourcePath
		}
	}
	callersByName := make(map[string][]string, len(results))
	for _, pf := range parsed {
		ast.Inspect(pf.node, func(n ast.Node) bool {
			ident, ok := n.(*ast.Ident)
			if !ok {
				return true
			}
			decl, isSentinel := declFile[ident.Name]
			if !isSentinel || pf.relPath == decl {
				return true
			}
			if len(callersByName[ident.Name]) >= 5 {
				return true
			}
			pos := fset.Position(ident.Pos())
			entry := fmt.Sprintf("%s#%d", pf.relPath, pos.Line)
			// Dedupe identical entries (same file+line visited once anyway,
			// but guard against repeated identical positions).
			for _, existing := range callersByName[ident.Name] {
				if existing == entry {
					return true
				}
			}
			callersByName[ident.Name] = append(callersByName[ident.Name], entry)
			return true
		})
	}
	for i := range results {
		results[i].Callers = callersByName[results[i].Name]
	}

	return results, err
}

// resolveCallersFromGraph fills Callers from CPG inbound edges: sentinel
// nodes are located by Name match, each inbound edge's source node
// contributes its FileSpec (path#LineStart, falling back to the edge's own
// LineNumber when the node carries no coordinates), excluding the
// declaration file, capped at 5 callers per sentinel in deterministic
// (sorted source-ID) order. Sentinels unknown to the graph keep empty caller
// lists.
func resolveCallersFromGraph(graph *akg.CodePropertyGraph, results []SentinelErrorFact) {
	declFile := make(map[string]string, len(results))
	for _, r := range results {
		if _, ok := declFile[r.Name]; !ok {
			declFile[r.Name] = r.SourcePath
		}
	}
	// Index node IDs by literal name (one scan; sentinels are few).
	idsByName := make(map[string][]string)
	if graph.Nodes != nil {
		graph.Nodes.Iterate(func(id string, node *link.ResolvedNode) {
			if node == nil || node.Name == "" {
				return
			}
			idsByName[node.Name] = append(idsByName[node.Name], id)
		})
	}
	for i := range results {
		var entries []string
		seen := make(map[string]bool)
		ids := append([]string(nil), idsByName[results[i].Name]...)
		sort.Strings(ids)
		for _, id := range ids {
			edges := append([]link.ResolvedEdge(nil), graph.GetInboundEdges(id)...)
			sort.Slice(edges, func(a, b int) bool { return edges[a].SourceID < edges[b].SourceID })
			for _, edge := range edges {
				src, ok := graph.GetNode(edge.SourceID)
				if !ok || src == nil {
					continue
				}
				path := filepath.ToSlash(src.FileSpec.Path)
				if path == "" || path == declFile[results[i].Name] {
					continue
				}
				line := src.FileSpec.LineStart
				if line <= 0 {
					line = edge.LineNumber
				}
				if line <= 0 {
					continue
				}
				entry := fmt.Sprintf("%s#%d", path, line)
				if seen[entry] {
					continue
				}
				seen[entry] = true
				entries = append(entries, entry)
				if len(entries) >= 5 {
					break
				}
			}
			if len(entries) >= 5 {
				break
			}
		}
		results[i].Callers = entries
	}
}
