package sre

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// PackageTestSummary records the testing surface for a given Go package.
type PackageTestSummary struct {
	Package     string   `json:"package"`
	Directory   string   `json:"directory"`
	TestFiles   int      `json:"test_files"`
	UnitTests   int      `json:"unit_tests"`
	Benchmarks  int      `json:"benchmarks"`
	EdgeCases   []string `json:"edge_cases"`
}

// GenerateTestTopology scans all test suites in the repository and generates
// docs/test_topology.md outlining test verification coverage and tested invariants.
func GenerateTestTopology(repoRoot string) (string, error) {
	summaries, err := scanTestTopology(repoRoot)
	if err != nil {
		return "", err
	}

	sort.Slice(summaries, func(i, j int) bool {
		return summaries[i].Package < summaries[j].Package
	})

	var sb strings.Builder
	sb.WriteString("# Test Topology & Verification Coverage Matrix\n\n")
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 31).\n")
	sb.WriteString("> Maps subsystem packages to guarding unit, integration, and benchmark suites.\n\n")

	sb.WriteString("| Target Package | Directory | Test Files | Tests | Benchmarks | Verified Edge Cases & Invariants |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- | :--- | :--- |\n")

	totalTests := 0
	totalFiles := 0

	for _, s := range summaries {
		edgeCasesStr := "Standard unit scenarios"
		if len(s.EdgeCases) > 0 {
			edgeCasesStr = strings.Join(s.EdgeCases, ", ")
		}

		totalTests += s.UnitTests
		totalFiles += s.TestFiles

		sb.WriteString(fmt.Sprintf("| **`%s`** | `%s` | %d | %d | %d | %s |\n",
			s.Package, s.Directory, s.TestFiles, s.UnitTests, s.Benchmarks, edgeCasesStr))
	}

	sb.WriteString(fmt.Sprintf("\n**Total Testing Surface:** %d test functions across %d test files in %d packages.\n",
		totalTests, totalFiles, len(summaries)))

	outPath := filepath.Join(repoRoot, "docs", "test_topology.md")
	result := sb.String()
	_, err = storage.AtomicWriteFile(outPath, []byte(result))
	return result, err
}

func scanTestTopology(repoRoot string) ([]PackageTestSummary, error) {
	byPkg := make(map[string]*PackageTestSummary)
	fset := token.NewFileSet()

	err := filepath.WalkDir(repoRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == ".glassmarble" || name == "vendor" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, "_test.go") {
			return nil
		}

		relPath, _ := filepath.Rel(repoRoot, path)
		relPath = filepath.ToSlash(relPath)
		dir := filepath.Dir(relPath)

		node, parseErr := parser.ParseFile(fset, path, nil, 0)
		if parseErr != nil {
			return nil
		}

		pkgName := strings.TrimSuffix(node.Name.Name, "_test")
		summary, ok := byPkg[dir]
		if !ok {
			summary = &PackageTestSummary{
				Package:   pkgName,
				Directory: dir,
			}
			byPkg[dir] = summary
		}

		summary.TestFiles++

		for _, decl := range node.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok {
				continue
			}

			name := fn.Name.Name
			if strings.HasPrefix(name, "Test") {
				summary.UnitTests++
				// Check for edge-case keywords
				lower := strings.ToLower(name)
				if strings.Contains(lower, "concurrent") || strings.Contains(lower, "error") ||
					strings.Contains(lower, "boundary") || strings.Contains(lower, "timeout") ||
					strings.Contains(lower, "fail") || strings.Contains(lower, "invalid") ||
					strings.Contains(lower, "unclosed") {
					if len(summary.EdgeCases) < 5 {
						summary.EdgeCases = append(summary.EdgeCases, fmt.Sprintf("`%s`", name))
					}
				}
			} else if strings.HasPrefix(name, "Benchmark") {
				summary.Benchmarks++
			}
		}

		return nil
	})

	var list []PackageTestSummary
	for _, s := range byPkg {
		list = append(list, *s)
	}
	return list, err
}
