package devex

import (
	"fmt"
	"os/exec"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// APIDelta tracks breaking or notable changes in public interfaces between two revisions.
type APIDelta struct {
	DeletedFunctions []string `json:"deleted_functions"`
	ModifiedSignatures []struct {
		Name   string `json:"name"`
		Before string `json:"before"`
		After  string `json:"after"`
	} `json:"modified_signatures"`
	RenamedFields []struct {
		OldName string `json:"old_name"`
		NewName string `json:"new_name"`
		Struct  string `json:"struct"`
	} `json:"renamed_fields"`
	// RenamedConfigVars pairs env vars that disappeared with similar new ones.
	RenamedConfigVars []struct {
		OldName string `json:"old_name"`
		NewName string `json:"new_name"`
	} `json:"renamed_config_vars"`
	// RemovedConfigVars lists env vars deleted with no similar replacement.
	RemovedConfigVars []string `json:"removed_config_vars"`
}

// GenerateMigrationGuide analyzes symbol and commit differences between two git refs
// and produces a comprehensive migration guide markdown document.
func GenerateMigrationGuide(repoRoot, ref1, ref2, outFile string) (string, error) {
	delta, commits, err := computeRevisionDiff(repoRoot, ref1, ref2)
	diffFailed := err != nil
	var diffErr error
	if diffFailed {
		diffErr = err
		commits = []string{fmt.Sprintf("Update between %s and %s", ref1, ref2)}
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Migration Guide: %s → %s\n\n", ref1, ref2))
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 24).\n")
	sb.WriteString(fmt.Sprintf("> Computed from AST symbol diffing and commit reasoning between `%s` and `%s`.\n\n", ref1, ref2))

	sb.WriteString("## Executive Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Source Reference:** `%s`\n", ref1))
	sb.WriteString(fmt.Sprintf("- **Target Reference:** `%s`\n", ref2))
	sb.WriteString(fmt.Sprintf("- **Generated On:** %s\n", time.Now().Format("2006-01-02 15:04:05 MST")))
	sb.WriteString(fmt.Sprintf("- **Breaking Changes Detected:** %d\n\n", len(delta.DeletedFunctions)+len(delta.ModifiedSignatures)+len(delta.RenamedFields)))

	// Section 1: Breaking Changes
	sb.WriteString("## Breaking Changes & Interface Deltas\n\n")

	if len(delta.DeletedFunctions) > 0 {
		sb.WriteString("### ⚠️ Deleted Public Functions & Methods\n\n")
		sb.WriteString("The following exported symbols were removed and are no longer available:\n\n")
		for _, fn := range delta.DeletedFunctions {
			sb.WriteString(fmt.Sprintf("- ❌ `func %s`\n", displayNameOf(fn)))
		}
		sb.WriteString("\n")
	}

	if len(delta.ModifiedSignatures) > 0 {
		sb.WriteString("### 🔄 Modified Function Signatures\n\n")
		sb.WriteString("| Function | Previous Signature | New Signature |\n")
		sb.WriteString("| :--- | :--- | :--- |\n")
		for _, sig := range delta.ModifiedSignatures {
			sb.WriteString(fmt.Sprintf("| **`%s`** | `%s` | `%s` |\n", displayNameOf(sig.Name), sig.Before, sig.After))
		}
		sb.WriteString("\n")
	}

	if len(delta.RenamedFields) > 0 {
		sb.WriteString("### 🏷️ Renamed Struct Fields & Parameters\n\n")
		sb.WriteString("| Struct | Old Field | New Field |\n")
		sb.WriteString("| :--- | :--- | :--- |\n")
		for _, f := range delta.RenamedFields {
			sb.WriteString(fmt.Sprintf("| `%s` | `~~%s~~` | `**%s**` |\n", f.Struct, f.OldName, f.NewName))
		}
		sb.WriteString("\n")
	}

	if diffFailed {
		// computeRevisionDiff failed (bad ref, unfetched tag, git error): delta
		// is the zero value, not a verified "nothing changed" result. Say so
		// explicitly rather than shipping a confident-looking "no breaking
		// changes" claim the tool never actually verified.
		sb.WriteString(fmt.Sprintf("⚠️ Automated interface diffing between `%s` and `%s` could not run (%v). "+
			"Breaking-change detection below is incomplete — review the interface manually.\n\n", ref1, ref2, diffErr))
	} else if len(delta.DeletedFunctions) == 0 && len(delta.ModifiedSignatures) == 0 && len(delta.RenamedFields) == 0 {
		sb.WriteString("✅ No breaking interface changes or deleted symbols detected in public surfaces.\n\n")
	}

	// Section 1b: Configuration variable renames (Pillar 24).
	if len(delta.RenamedConfigVars) > 0 {
		sb.WriteString("### 🔧 Renamed Configuration Variables\n\n")
		sb.WriteString("| Old Variable | New Variable |\n")
		sb.WriteString("| :--- | :--- |\n")
		for _, r := range delta.RenamedConfigVars {
			sb.WriteString(fmt.Sprintf("| `~~%s~~` | `**%s**` |\n", r.OldName, r.NewName))
		}
		sb.WriteString("\n")
	}
	if len(delta.RemovedConfigVars) > 0 {
		sb.WriteString("### 🗑️ Removed Configuration Variables\n\n")
		sb.WriteString("The following environment variables were removed with no replacement:\n\n")
		for _, v := range delta.RemovedConfigVars {
			sb.WriteString(fmt.Sprintf("- ❌ `%s`\n", v))
		}
		sb.WriteString("\n")
	}

	// Section 1c: Migration code examples — Before/After call sites per modified signature.
	if len(delta.ModifiedSignatures) > 0 {
		sb.WriteString("## Migration Code Examples\n\n")
		for _, sig := range delta.ModifiedSignatures {
			short := displayNameOf(sig.Name)
			sb.WriteString(fmt.Sprintf("### `%s`\n\n", short))
			sb.WriteString("Update call sites from:\n\n")
			sb.WriteString("```go\n")
			sb.WriteString(fmt.Sprintf("// before: %s\nout := %s(/* update args */)\n", sig.Before, short))
			sb.WriteString("```\n\n")
			sb.WriteString("to:\n\n")
			sb.WriteString("```go\n")
			sb.WriteString(fmt.Sprintf("// after: %s\nout := %s(/* update args */)\n", sig.After, short))
			sb.WriteString("```\n\n")
			sb.WriteString(fmt.Sprintf("> Rewrite note: update arguments at call sites of `%s` to match the new signature `%s`.\n\n", short, sig.After))
		}
	}

	// Section 2: Commit History
	sb.WriteString("## Commit History & Architectural Intent\n\n")
	for _, c := range commits {
		if strings.TrimSpace(c) != "" {
			sb.WriteString(fmt.Sprintf("- %s\n", c))
		}
	}
	sb.WriteString("\n")

	// Section 3: Recommended Upgrade Steps
	sb.WriteString("## Recommended Upgrade Steps\n\n")
	sb.WriteString(fmt.Sprintf("1. Update repository dependency or check out `%s`.\n", ref2))
	sb.WriteString("2. Compile and run test suite: `go test ./...`.\n")
	sb.WriteString("3. Synchronize living documentation: `gmb doc`.\n")
	sb.WriteString("4. Verify zero documentation drift: `gmb doc check`.\n")

	result := sb.String()
	if outFile != "" {
		if _, err := storage.AtomicWriteFile(outFile, []byte(result)); err != nil {
			return "", err
		}
	}

	return result, nil
}

func computeRevisionDiff(repoRoot, ref1, ref2 string) (APIDelta, []string, error) {
	delta := APIDelta{}
	cmd := exec.Command("git", "log", fmt.Sprintf("%s..%s", ref1, ref2), "--oneline")
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		return delta, nil, err
	}

	lines := strings.Split(strings.TrimSpace(string(out)), "\n")

	// AKG symbol diffing per Pillar 24: extract exported symbols at each ref
	// via `git show <ref>:<go-file>` so renames/deletions/signature changes
	// are detected deterministically without checking out the old tree.
	before := extractExportedSymbolsAtRef(repoRoot, ref1)
	after := extractExportedSymbolsAtRef(repoRoot, ref2)

	for fn, beforeSig := range before {
		afterSig, ok := after[fn]
		if !ok {
			delta.DeletedFunctions = append(delta.DeletedFunctions, fn)
			continue
		}
		if normalizeSig(beforeSig) != normalizeSig(afterSig) {
			delta.ModifiedSignatures = append(delta.ModifiedSignatures, struct {
				Name   string `json:"name"`
				Before string `json:"before"`
				After  string `json:"after"`
			}{Name: fn, Before: beforeSig, After: afterSig})
		}
	}

	// Struct field renames: heuristic — a field deleted from a struct at
	// ref1 that has a same-typed new field at ref2 is reported as renamed.
	beforeFields := extractStructFieldsAtRef(repoRoot, ref1)
	afterFields := extractStructFieldsAtRef(repoRoot, ref2)
	for st, bf := range beforeFields {
		af, ok := afterFields[st]
		if !ok {
			continue
		}
		for oldName, oldType := range bf {
			if _, stillThere := af[oldName]; stillThere {
				continue
			}
			for newName, newType := range af {
				if _, wasThere := bf[newName]; wasThere {
					continue
				}
				if newType == oldType {
					delta.RenamedFields = append(delta.RenamedFields, struct {
						OldName string `json:"old_name"`
						NewName string `json:"new_name"`
						Struct  string `json:"struct"`
					}{OldName: oldName, NewName: newName, Struct: st})
					break
				}
			}
		}
	}

	// Fallback: if neither ref resolves (shallow clone, missing ref), fall
	// back to parsing the unified diff for deleted exported funcs so the
	// guide still reports breaking changes instead of "no changes".
	if len(before) == 0 && len(after) == 0 {
		delta = diffFallbackDelta(repoRoot, ref1, ref2)
	}

	// Config-var renames: diff env-var sets observed in the unified diff
	// between the two refs (Pillar 24). Runs regardless of the symbol-diff
	// path above since it only needs `git diff` output.
	renamed, removedVars := diffConfigVarRenames(repoRoot, ref1, ref2)
	delta.RenamedConfigVars = renamed
	delta.RemovedConfigVars = removedVars

	return delta, lines, nil
}

// ────────────────────────────────────────────────────────────────────────────
// Symbol extraction at a git ref (deterministic, no checkout required)
// ────────────────────────────────────────────────────────────────────────────

// listGoFilesAtRef returns repo-relative .go paths visible at the given ref.
func listGoFilesAtRef(repoRoot, ref string) []string {
	cmd := exec.Command("git", "ls-tree", "-r", "--name-only", ref)
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		return nil
	}
	var files []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasSuffix(line, ".go") && !strings.HasSuffix(line, "_test.go") {
			files = append(files, line)
		}
	}
	return files
}

// showFileAtRef returns the content of path as it existed at ref.
func showFileAtRef(repoRoot, ref, path string) (string, bool) {
	cmd := exec.Command("git", "show", ref+":"+path)
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		return "", false
	}
	return string(out), true
}

// extractExportedSymbolsAtRef maps exported func/method name → signature line.
// Keys are file-qualified (path::Recv.Name) so same-named symbols in
// different packages never collide; display names strip the file prefix.
func extractExportedSymbolsAtRef(repoRoot, ref string) map[string]string {
	result := make(map[string]string)
	for _, f := range listGoFilesAtRef(repoRoot, ref) {
		content, ok := showFileAtRef(repoRoot, ref, f)
		if !ok {
			continue
		}
		for _, line := range strings.Split(content, "\n") {
			trimmed := strings.TrimSpace(line)
			if !strings.HasPrefix(trimmed, "func ") {
				continue
			}
			name := exportedFuncName(trimmed)
			if name == "" {
				continue
			}
			key := f + "::" + name
			if _, exists := result[key]; !exists {
				result[key] = trimmed
			}
		}
	}
	return result
}

// extractStructFieldsAtRef maps struct name → field name → field type.
// Keys are file-qualified (path::Struct) for the same reason as above.
func extractStructFieldsAtRef(repoRoot, ref string) map[string]map[string]string {
	result := make(map[string]map[string]string)
	for _, f := range listGoFilesAtRef(repoRoot, ref) {
		content, ok := showFileAtRef(repoRoot, ref, f)
		if !ok {
			continue
		}
		lines := strings.Split(content, "\n")
		var curStruct string
		inStruct := false
		braceDepth := 0
		for _, line := range lines {
			trimmed := strings.TrimSpace(line)
			if !inStruct {
				if st, ok := parseTypeStructLine(trimmed); ok && isExportedGoIdent(st) {
					curStruct = st
					inStruct = true
					braceDepth = strings.Count(line, "{") - strings.Count(line, "}")
					if _, exists := result[curStruct]; !exists {
						result[curStruct] = make(map[string]string)
					}
					continue
				}
				continue
			}
			braceDepth += strings.Count(line, "{") - strings.Count(line, "}")
			if braceDepth <= 0 {
				inStruct = false
				curStruct = ""
				continue
			}
			if trimmed == "" || strings.HasPrefix(trimmed, "//") {
				continue
			}
			fields := strings.Fields(trimmed)
			if len(fields) >= 2 && isExportedGoIdent(fields[0]) {
				result[curStruct][fields[0]] = fields[1]
			}
		}
	}
	return result
}

// diffFallbackDelta parses the unified diff when ref content is unavailable.
func diffFallbackDelta(repoRoot, ref1, ref2 string) APIDelta {
	delta := APIDelta{}
	cmd := exec.Command("git", "diff", ref1, ref2, "--", "*.go")
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		return delta
	}
	removed := make(map[string]string)
	added := make(map[string]string)
	for _, line := range strings.Split(string(out), "\n") {
		if len(line) < 2 {
			continue
		}
		marker, body := line[0], strings.TrimSpace(line[1:])
		if !strings.HasPrefix(body, "func ") {
			continue
		}
		name := exportedFuncName(body)
		if name == "" {
			continue
		}
		switch marker {
		case '-':
			removed[name] = body
		case '+':
			added[name] = body
		}
	}
	for name, before := range removed {
		after, ok := added[name]
		if !ok {
			delta.DeletedFunctions = append(delta.DeletedFunctions, name)
			continue
		}
		if normalizeSig(before) != normalizeSig(after) {
			delta.ModifiedSignatures = append(delta.ModifiedSignatures, struct {
				Name   string `json:"name"`
				Before string `json:"before"`
				After  string `json:"after"`
			}{Name: name, Before: before, After: after})
		}
	}
	return delta
}

// ────────────────────────────────────────────────────────────────────────────
// Config-var rename detection (Pillar 24)
//
// Env-var names are extracted from added/removed lines of
// `git diff ref1 ref2 -U0 -- *.go` by parsing +lines/-lines for
// os.Getenv("X") / os.LookupEnv("X"). The removed-minus-added set and the
// added-minus-removed set are diffed: removed+added pairs with similarity
// (same prefix before the first '_' or levenshtein distance <= 3) are
// reported as renames; unpaired removed vars are pure deletions.
// ────────────────────────────────────────────────────────────────────────────

var getenvRe = regexp.MustCompile(`(?:Getenv|LookupEnv)\(\s*"([A-Z_][A-Z0-9_]*)"\s*[,)]`)

// diffConfigVarRenames returns (renamed pairs, pure removals) between two refs.
func diffConfigVarRenames(repoRoot, ref1, ref2 string) ([]struct {
	OldName string `json:"old_name"`
	NewName string `json:"new_name"`
}, []string) {
	cmd := exec.Command("git", "diff", ref1, ref2, "-U0", "--", "*.go")
	cmd.Dir = repoRoot
	out, err := cmd.Output()
	if err != nil {
		return nil, nil
	}
	removedSet := make(map[string]bool)
	addedSet := make(map[string]bool)
	for _, line := range strings.Split(string(out), "\n") {
		if len(line) < 2 {
			continue
		}
		marker := line[0]
		if marker != '+' && marker != '-' {
			continue
		}
		if strings.HasPrefix(line, "+++") || strings.HasPrefix(line, "---") {
			continue
		}
		for _, m := range getenvRe.FindAllStringSubmatch(line[1:], -1) {
			if len(m) < 2 {
				continue
			}
			if marker == '-' {
				removedSet[m[1]] = true
			} else {
				addedSet[m[1]] = true
			}
		}
	}
	var removed, added []string
	for v := range removedSet {
		if !addedSet[v] {
			removed = append(removed, v)
		}
	}
	for v := range addedSet {
		if !removedSet[v] {
			added = append(added, v)
		}
	}
	sort.Strings(removed)
	sort.Strings(added)

	type rename struct {
		OldName string `json:"old_name"`
		NewName string `json:"new_name"`
	}
	var renamedPairs []rename
	used := make(map[string]bool)
	var pureRemoved []string
	for _, old := range removed {
		best := ""
		bestDist := -1
		for _, nw := range added {
			if used[nw] {
				continue
			}
			if !similarEnvName(old, nw) {
				continue
			}
			d := levenshtein(old, nw)
			if best == "" || d < bestDist {
				best = nw
				bestDist = d
			}
		}
		if best != "" {
			renamedPairs = append(renamedPairs, rename{OldName: old, NewName: best})
			used[best] = true
		} else {
			pureRemoved = append(pureRemoved, old)
		}
	}
	sort.Strings(pureRemoved)
	// Convert to the APIDelta anonymous struct type (identical fields+tags).
	renamed := make([]struct {
		OldName string `json:"old_name"`
		NewName string `json:"new_name"`
	}, 0, len(renamedPairs))
	for _, r := range renamedPairs {
		renamed = append(renamed, struct {
			OldName string `json:"old_name"`
			NewName string `json:"new_name"`
		}{OldName: r.OldName, NewName: r.NewName})
	}
	return renamed, pureRemoved
}

// similarEnvName reports whether two env-var names look like a rename:
// same prefix before the first '_' (e.g. OAUTH_* → OAUTH_*) or
// levenshtein distance <= 3 (e.g. PORT → PORTS, DB_HOST → DB_HOSTS).
func similarEnvName(a, b string) bool {
	if prefixBeforeUnderscore(a) == prefixBeforeUnderscore(b) && prefixBeforeUnderscore(a) != "" {
		return true
	}
	return levenshtein(a, b) <= 3
}

func prefixBeforeUnderscore(s string) string {
	if idx := strings.Index(s, "_"); idx > 0 {
		return s[:idx]
	}
	return s
}

// levenshtein returns the edit distance between two strings (small,
// allocation-light implementation for short env-var names).
func levenshtein(a, b string) int {
	ar, br := []rune(a), []rune(b)
	if len(ar) == 0 {
		return len(br)
	}
	if len(br) == 0 {
		return len(ar)
	}
	prev := make([]int, len(br)+1)
	for j := range prev {
		prev[j] = j
	}
	for i := 1; i <= len(ar); i++ {
		cur := make([]int, len(br)+1)
		cur[0] = i
		for j := 1; j <= len(br); j++ {
			cost := 0
			if ar[i-1] != br[j-1] {
				cost = 1
			}
			cur[j] = min3(prev[j]+1, cur[j-1]+1, prev[j-1]+cost)
		}
		prev = cur
	}
	return prev[len(br)]
}

func min3(a, b, c int) int {
	if a > b {
		a = b
	}
	if a > c {
		a = c
	}
	return a
}

func exportedFuncName(sigLine string) string {
	// Forms: "func Name(...", "func (r Recv) Name(...".
	// Key includes the receiver so methods on different types never
	// collide (e.g. (*A).Render vs (*B).Render are distinct symbols).
	rest := strings.TrimPrefix(sigLine, "func ")
	rest = strings.TrimSpace(rest)
	receiver := ""
	if strings.HasPrefix(rest, "(") {
		if idx := strings.Index(rest, ")"); idx >= 0 {
			receiver = strings.TrimSpace(rest[:idx+1])
			rest = strings.TrimSpace(rest[idx+1:])
		}
	}
	fields := strings.Fields(rest)
	if len(fields) == 0 {
		return ""
	}
	name := strings.Split(fields[0], "(")[0]
	if !isExportedGoIdent(name) {
		return ""
	}
	if receiver != "" {
		recvType := receiver
		recvType = strings.TrimPrefix(recvType, "(")
		recvType = strings.TrimSuffix(recvType, ")")
		recvFields := strings.Fields(recvType)
		if len(recvFields) == 2 {
			recvType = recvFields[1]
		} else if len(recvFields) == 1 {
			recvType = recvFields[0]
		}
		recvType = strings.TrimPrefix(recvType, "*")
		return recvType + "." + name
	}
	return name
}

func parseTypeStructLine(line string) (string, bool) {
	// "type Name struct {" with optional spacing.
	if !strings.HasPrefix(line, "type ") || !strings.Contains(line, "struct") {
		return "", false
	}
	fields := strings.Fields(strings.TrimPrefix(line, "type "))
	if len(fields) == 0 {
		return "", false
	}
	return fields[0], true
}

func isExportedGoIdent(name string) bool {
	if name == "" {
		return false
	}
	c := name[0]
	return c >= 'A' && c <= 'Z'
}

func normalizeSig(s string) string {
	s = strings.Join(strings.Fields(s), " ")
	replacer := strings.NewReplacer("( ", "(", " )", ")", " ,", ",")
	prev := ""
	for s != prev {
		prev = s
		s = replacer.Replace(s)
	}
	return s
}

// displayNameOf strips the file-qualification prefix (path::Name → Name)
// for human-readable rendering.
func displayNameOf(key string) string {
	if idx := strings.LastIndex(key, "::"); idx >= 0 {
		return key[idx+2:]
	}
	return key
}
