package federation

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// I18nSummary reports on localization key coverage and missing translations.
type I18nSummary struct {
	TotalKeysInCode   int                 `json:"total_keys_in_code"`
	SupportedLocales  []string            `json:"supported_locales"`
	CoverageByLocale  map[string]float64  `json:"coverage_by_locale"`
	MissingKeys       map[string][]string `json:"missing_keys"`
}

// GenerateI18nInventory scans code for localization lookups and compares against
// locale bundle files, writing the audit report to docs/i18n.md.
func GenerateI18nInventory(repoRoot string) (string, error) {
	codeKeys, err := scanCodeTranslationKeys(repoRoot)
	if err != nil {
		return "", err
	}

	localeBundles := loadLocaleBundles(repoRoot)
	summary := I18nSummary{
		TotalKeysInCode:  len(codeKeys),
		CoverageByLocale: make(map[string]float64),
		MissingKeys:      make(map[string][]string),
	}

	for loc, bundleKeys := range localeBundles {
		summary.SupportedLocales = append(summary.SupportedLocales, loc)
		foundCount := 0
		for k := range codeKeys {
			if bundleKeys[k] {
				foundCount++
			} else {
				summary.MissingKeys[loc] = append(summary.MissingKeys[loc], k)
			}
		}

		cov := 100.0
		if len(codeKeys) > 0 {
			cov = float64(foundCount) / float64(len(codeKeys)) * 100.0
		}
		summary.CoverageByLocale[loc] = cov
	}
	sort.Strings(summary.SupportedLocales)

	var sb strings.Builder
	sb.WriteString("# Internationalization (i18n) & Localization Inventory\n\n")
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 35).\n")
	sb.WriteString("> Audits code translation key usage against locale bundles to ensure zero missing strings.\n\n")

	sb.WriteString("## Coverage Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Total Translation Keys in Code:** %d\n", summary.TotalKeysInCode))
	sb.WriteString(fmt.Sprintf("- **Locales Detected:** %d (%s)\n\n", len(summary.SupportedLocales), strings.Join(summary.SupportedLocales, ", ")))

	sb.WriteString("| Locale | Coverage | Status | Missing Keys Count |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- |\n")

	if len(summary.SupportedLocales) == 0 {
		sb.WriteString("| `en` (source) | 100.0% | 🟢 Source Code Baseline | 0 |\n\n")
	} else {
		for _, loc := range summary.SupportedLocales {
			cov := summary.CoverageByLocale[loc]
			status := "🟢 Fully Localized"
			if cov < 80.0 {
				status = "🔴 Incomplete Coverage"
			} else if cov < 100.0 {
				status = "🟡 Minor Drift"
			}
			sb.WriteString(fmt.Sprintf("| `%s` | %.1f%% | %s | %d |\n", loc, cov, status, len(summary.MissingKeys[loc])))
		}
		sb.WriteString("\n")
	}

	// Orphaned keys: present in bundles but no longer referenced in code.
	orphaned := orphanedKeys(codeKeys, localeBundles)
	if len(orphaned) > 0 {
		sb.WriteString("## Orphaned Keys (in bundles, unused in code)\n\n")
		sb.WriteString("These keys can be pruned from locale bundles:\n\n")
		for _, k := range orphaned {
			sb.WriteString(fmt.Sprintf("- `%s`\n", k))
		}
		sb.WriteString("\n")
	}

	// Missing keys detail per locale.
	hasMissing := false
	for _, loc := range summary.SupportedLocales {
		if len(summary.MissingKeys[loc]) > 0 {
			hasMissing = true
			break
		}
	}
	if hasMissing {
		sb.WriteString("## Missing Keys by Locale\n\n")
		for _, loc := range summary.SupportedLocales {
			missing := summary.MissingKeys[loc]
			if len(missing) == 0 {
				continue
			}
			sort.Strings(missing)
			sb.WriteString(fmt.Sprintf("### `%s` — %d missing\n\n", loc, len(missing)))
			for _, k := range missing {
				sb.WriteString(fmt.Sprintf("- `%s`\n", k))
			}
			sb.WriteString("\n")
		}
	}

	outPath := filepath.Join(repoRoot, "docs", "i18n.md")
	result := sb.String()
	_, err = storage.AtomicWriteFile(outPath, []byte(result))
	return result, err
}

func scanCodeTranslationKeys(repoRoot string) (map[string]bool, error) {
	keys := make(map[string]bool)
	fset := token.NewFileSet()

	err := filepath.WalkDir(repoRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil || d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		node, parseErr := parser.ParseFile(fset, path, nil, 0)
		if parseErr != nil {
			return nil
		}

		ast.Inspect(node, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}

			fnStr := ""
			qualifier := ""
			switch t := call.Fun.(type) {
			case *ast.Ident:
				fnStr = t.Name
			case *ast.SelectorExpr:
				fnStr = t.Sel.Name
				if ident, ok := t.X.(*ast.Ident); ok {
					qualifier = ident.Name
				}
			}

			if isTranslationCall(fnStr, qualifier) {
				if len(call.Args) > 0 {
					if lit, ok := call.Args[0].(*ast.BasicLit); ok {
						val := strings.Trim(lit.Value, `"`)
						keys[val] = true
					}
				}
			}
			return true
		})
		return nil
	})

	return keys, err
}

// orphanedKeys returns bundle keys not referenced anywhere in code.
func orphanedKeys(codeKeys map[string]bool, bundles map[string]map[string]bool) []string {
	seen := make(map[string]bool)
	var out []string
	for _, bundleKeys := range bundles {
		for k := range bundleKeys {
			if !codeKeys[k] && !seen[k] {
				seen[k] = true
				out = append(out, k)
			}
		}
	}
	sort.Strings(out)
	return out
}

// isTranslationCall reports whether a call is a localization lookup.
// Covers go-i18n, nicksnyder, message.Printer, gettext, and common wrappers.
func isTranslationCall(fn, qualifier string) bool {
	switch fn {
	case "T", "Translate", "Localize", "Gettext", "Ngettext", "MustLocalize", "LocalizeWithPlural":
		return true
	}
	// message.NewPrinter(lang).Printf/Sprintf/Fprintf — qualifier is the printer var.
	if qualifier == "printer" || qualifier == "p" || strings.Contains(strings.ToLower(qualifier), "printer") || strings.Contains(strings.ToLower(qualifier), "localizer") || strings.Contains(strings.ToLower(qualifier), "bundle") {
		if fn == "Printf" || fn == "Sprintf" || fn == "Fprintf" || fn == "Print" {
			return true
		}
	}
	if qualifier == "i18n" || qualifier == "trans" || qualifier == "locale" {
		return true
	}
	return false
}

func loadLocaleBundles(repoRoot string) map[string]map[string]bool {
	bundles := make(map[string]map[string]bool)
	for _, locDir := range []string{"locales", "lang", "translations", "i18n", filepath.Join("assets", "locales")} {
		loadBundleDir(filepath.Join(repoRoot, locDir), bundles)
	}
	return bundles
}

func loadBundleDir(locDir string, bundles map[string]map[string]bool) {
	entries, err := os.ReadDir(locDir)
	if err != nil {
		return
	}

	for _, e := range entries {
		name := e.Name()
		var locName string
		switch {
		case strings.HasSuffix(name, ".json"):
			locName = strings.TrimSuffix(name, ".json")
		case strings.HasSuffix(name, ".yaml") || strings.HasSuffix(name, ".yml"):
			locName = strings.TrimSuffix(strings.TrimSuffix(name, ".yaml"), ".yml")
		case strings.HasSuffix(name, ".toml"):
			locName = strings.TrimSuffix(name, ".toml")
		default:
			continue
		}
		filePath := filepath.Join(locDir, name)
		data, err := os.ReadFile(filePath)
		if err != nil {
			continue
		}
		var raw map[string]interface{}
		if err := json.Unmarshal(data, &raw); err != nil {
			continue
		}
		set := bundles[locName]
		if set == nil {
			set = make(map[string]bool)
			bundles[locName] = set
		}
		for k := range raw {
			set[k] = true
		}
	}
}
