package federation

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	docconfig "github.com/Syamchand123/GlassMarble/internal/doc_engine/config"
	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// ServiceManifest represents a public federation schema exported by a GlassMarble service repo.
type ServiceManifest struct {
	ServiceName     string           `json:"service_name"`
	Version         string           `json:"version"`
	ExportedAt      string           `json:"exported_at"`
	APISurface      []APISurfaceItem `json:"api_surface"`
	ManagedDocs     []string         `json:"managed_docs"`
	Schemas         []string         `json:"schemas"`
}

// APISurfaceItem documents an endpoint, RPC, or interface exported across repository boundaries.
type APISurfaceItem struct {
	Kind        string `json:"kind"` // HTTP, gRPC, CLI, Event
	Identifier  string `json:"identifier"`
	Description string `json:"description"`
}

// ExportFederationManifest exports .glassmarble/manifest.json for cross-repo consumption.
func ExportFederationManifest(repoRoot string) (string, error) {
	cfg, err := docconfig.LoadDocsConfig(repoRoot)
	if err != nil {
		return "", err
	}

	manifest := ServiceManifest{
		ServiceName: filepath.Base(repoRoot),
		Version:     "1.0.0",
		ExportedAt:  time.Now().UTC().Format(time.RFC3339),
		APISurface: []APISurfaceItem{
			{Kind: "CLI", Identifier: "gmb analyze", Description: "Architecture Knowledge Graph generation"},
			{Kind: "CLI", Identifier: "gmb doc", Description: "Documentation Intelligence Engine"},
			{Kind: "CLI", Identifier: "gmb visualize", Description: "Architecture diagrams and export"},
		},
	}

	for _, d := range cfg.Documents {
		manifest.ManagedDocs = append(manifest.ManagedDocs, d.TargetPath)
	}

	data, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return "", err
	}

	outPath := filepath.Join(repoRoot, ".glassmarble", "manifest.json")
	_, err = storage.AtomicWriteFile(outPath, data)
	return outPath, err
}

// ImportFederationManifest parses an external service manifest and generates
// docs/federation/<serviceName>.md to document cross-repository client boundaries.
func ImportFederationManifest(repoRoot, serviceName, manifestPath string) (string, error) {
	data, err := os.ReadFile(manifestPath)
	if err != nil {
		return "", fmt.Errorf("reading external manifest: %w", err)
	}

	var manifest ServiceManifest
	if err := json.Unmarshal(data, &manifest); err != nil {
		return "", fmt.Errorf("parsing external manifest: %w", err)
	}

	if serviceName == "" {
		serviceName = manifest.ServiceName
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Federated Service Integration: %s\n\n", serviceName))
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 29).\n")
	sb.WriteString(fmt.Sprintf("> Cross-repository microservice boundaries imported from `%s`.\n\n", manifestPath))

	sb.WriteString("## Exported API Surface & Endpoints\n\n")
	sb.WriteString("| Kind | Identifier / Contract | Description |\n")
	sb.WriteString("| :--- | :--- | :--- |\n")

	for _, item := range manifest.APISurface {
		sb.WriteString(fmt.Sprintf("| `%s` | **`%s`** | %s |\n", item.Kind, item.Identifier, item.Description))
	}
	sb.WriteString("\n")

	if len(manifest.ManagedDocs) > 0 {
		sb.WriteString("## Upstream Documentation Links\n\n")
		for _, doc := range manifest.ManagedDocs {
			sb.WriteString(fmt.Sprintf("- 📄 `%s`\n", doc))
		}
		sb.WriteString("\n")
	}

	outDir := filepath.Join(repoRoot, "docs", "federation")
	_ = os.MkdirAll(outDir, 0755)
	outFile := filepath.Join(outDir, fmt.Sprintf("%s.md", serviceName))

	result := sb.String()
	_, err = storage.AtomicWriteFile(outFile, []byte(result))
	return result, err
}
