package federation

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// SnapshotResult contains metadata about a versioned doc freeze.
type SnapshotResult struct {
	VersionTag string   `json:"version_tag"`
	FilesCount int      `json:"files_count"`
	TargetDir  string   `json:"target_dir"`
	IndexFile  string   `json:"index_file"`
	Snapshots  []string `json:"snapshots"`
}

// SnapshotDocSuite freezes the current documentation suite into docs/versions/<versionTag>/
// and updates the version index navigation.
func SnapshotDocSuite(repoRoot, versionTag string) (SnapshotResult, error) {
	if versionTag == "" {
		versionTag = fmt.Sprintf("v%s", time.Now().Format("2006.01.02"))
	}
	if !strings.HasPrefix(versionTag, "v") {
		versionTag = "v" + versionTag
	}

	docsDir := filepath.Join(repoRoot, "docs")
	destDir := filepath.Join(docsDir, "versions", versionTag)
	if err := os.MkdirAll(destDir, 0755); err != nil {
		return SnapshotResult{}, fmt.Errorf("creating version snapshot directory: %w", err)
	}

	filesCopied := 0

	err := filepath.WalkDir(docsDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			if d.Name() == "versions" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".md") {
			return nil
		}

		rel, _ := filepath.Rel(docsDir, path)
		targetFile := filepath.Join(destDir, rel)
		_ = os.MkdirAll(filepath.Dir(targetFile), 0755)

		data, err := os.ReadFile(path)
		if err != nil {
			return nil
		}

		// Inject snapshot header into frontmatter if present
		content := string(data)
		if strings.HasPrefix(content, "---\n") {
			content = strings.Replace(content, "---\n", fmt.Sprintf("---\nsnapshot_version: %s\nsnapshot_date: %s\n", versionTag, time.Now().Format("2006-01-02")), 1)
		}

		if _, err := storage.AtomicWriteFile(targetFile, []byte(content)); err == nil {
			filesCopied++
		}

		return nil
	})
	if err != nil {
		return SnapshotResult{}, err
	}

	// Update docs/versions/index.md
	versionsDir := filepath.Join(docsDir, "versions")
	entries, _ := os.ReadDir(versionsDir)
	var allVersions []string
	for _, e := range entries {
		if e.IsDir() {
			allVersions = append(allVersions, e.Name())
		}
	}
	sort.Sort(sort.Reverse(sort.StringSlice(allVersions)))

	var sb strings.Builder
	sb.WriteString("# Documentation Version Matrix & Historical Snapshots\n\n")
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 27).\n")
	sb.WriteString("> Live documentation is actively maintained in `docs/`. Historical snapshots are frozen below.\n\n")

	sb.WriteString("| Version Snapshot | Release Tag | Snapshot Directory | Status |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- |\n")
	sb.WriteString("| **Latest (HEAD)** | `main` | `docs/` | 🟢 Active (Living) |\n")

	for _, v := range allVersions {
		sb.WriteString(fmt.Sprintf("| **%s** | `%s` | `docs/versions/%s/` | ❄️ Frozen Snapshot |\n", v, v, v))
	}

	indexPath := filepath.Join(versionsDir, "index.md")
	_, _ = storage.AtomicWriteFile(indexPath, []byte(sb.String()))

	return SnapshotResult{
		VersionTag: versionTag,
		FilesCount: filesCopied,
		TargetDir:  filepath.ToSlash(filepath.Join("docs", "versions", versionTag)),
		IndexFile:  filepath.ToSlash(filepath.Join("docs", "versions", "index.md")),
		Snapshots:  allVersions,
	}, nil
}
