// Package archfeatures implements Phase 6 Architectural Auto-Features:
// - Pillar 16: Autonomous Living ADR Generation
// - Pillar 30: Architectural Time Machine / Evolution Chapter
// - Pillar 28: Ubiquitous Language & DDD Domain Glossary
package archfeatures

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// ADREvent represents an architectural milestone event detected by the engine.
type ADREvent struct {
	Type        string // e.g. "COMPONENT_SPLIT", "NEW_DATABASE_LAYER", "CYCLE_RESOLVED", "NEW_SUBSYSTEM"
	Title       string
	Context     string
	Decision    string
	Consequence string
	CommitHash  string
	Author      string
	Timestamp   time.Time
}

// GenerateADR scaffolds an Architecture Decision Record (ADR) file under docs/adr/.
// It numbers the ADR sequentially (e.g. 0001-component-split.md).
func GenerateADR(repoRoot string, event ADREvent) (string, error) {
	adrDir := filepath.Join(repoRoot, "docs", "adr")
	if err := os.MkdirAll(adrDir, 0755); err != nil {
		return "", fmt.Errorf("creating adr directory: %w", err)
	}

	nextNum := getNextADRNumber(adrDir)
	slug := slugify(event.Title)
	if slug == "" {
		slug = strings.ToLower(strings.ReplaceAll(event.Type, "_", "-"))
	}

	filename := fmt.Sprintf("%04d-%s.md", nextNum, slug)
	targetPath := filepath.Join(adrDir, filename)

	dateStr := event.Timestamp.Format("2006-01-02")
	if event.Timestamp.IsZero() {
		dateStr = time.Now().Format("2006-01-02")
	}

	content := fmt.Sprintf(`---
id: adr-%04d
title: "%04d - %s"
status: accepted
date: %s
event_type: %s
commit: "%s"
---

# %04d. %s

## Status

Accepted (auto-generated by GlassMarble on architectural milestone)

## Context

%s

## Decision

%s

## Consequences

%s

## Timeline & Provenance

- **Event:** `+"`%s`"+`
- **Detected at commit:** `+"`%s`"+`
- **Date:** %s
`, nextNum, nextNum, event.Title, dateStr, event.Type, event.CommitHash,
		nextNum, event.Title,
		event.Context,
		event.Decision,
		event.Consequence,
		event.Type,
		event.CommitHash,
		dateStr)

	if _, err := storage.AtomicWriteFile(targetPath, []byte(content)); err != nil {
		return "", fmt.Errorf("writing adr file %s: %w", filename, err)
	}

	return filepath.ToSlash(filepath.Join("docs", "adr", filename)), nil
}

func getNextADRNumber(adrDir string) int {
	entries, err := os.ReadDir(adrDir)
	if err != nil {
		return 1
	}

	re := regexp.MustCompile(`^(\d{4})-`)
	highest := 0
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		matches := re.FindStringSubmatch(e.Name())
		if len(matches) == 2 {
			if n, err := strconv.Atoi(matches[1]); err == nil && n > highest {
				highest = n
			}
		}
	}
	return highest + 1
}

var nonAlphaRe = regexp.MustCompile(`[^a-z0-9]+`)

func slugify(s string) string {
	s = strings.ToLower(s)
	s = nonAlphaRe.ReplaceAllString(s, "-")
	return strings.Trim(s, "-")
}

// ScanArchEvents inspects git commit messages and architecture records to find candidate ADR events.
func ScanArchEvents(commitLogs []string) []ADREvent {
	var events []ADREvent
	for _, log := range commitLogs {
		lower := strings.ToLower(log)
		var evType string
		var title string
		var decision string

		if strings.Contains(lower, "split") && (strings.Contains(lower, "package") || strings.Contains(lower, "module") || strings.Contains(lower, "subsystem")) {
			evType = "COMPONENT_SPLIT"
			title = "Subsystem Decoupling & Component Split"
			decision = "Separated concerns into autonomous domain subpackages to eliminate architectural coupling."
		} else if strings.Contains(lower, "database") || strings.Contains(lower, "storage") || strings.Contains(lower, "schema") {
			evType = "NEW_DATABASE_LAYER"
			title = "Introduction of Storage & Persistence Layer"
			decision = "Adopted standardized persistence patterns with MVCC file locking and atomic writes."
		} else if strings.Contains(lower, "cycle") && (strings.Contains(lower, "break") || strings.Contains(lower, "resolve")) {
			evType = "CYCLE_RESOLVED"
			title = "Resolution of Dependency Cycle"
			decision = "Inverted dependency relationships to establish an acyclic package hierarchy."
		}

		if evType != "" {
			events = append(events, ADREvent{
				Type:        evType,
				Title:       title,
				Context:     fmt.Sprintf("Architectural change detected in commit log: %s", log),
				Decision:    decision,
				Consequence: "Reduces coupling, clarifies module boundaries, and improves testability.",
				Timestamp:   time.Now(),
			})
		}
	}
	return events
}
