// Package archfeatures implements Phase 6 Architectural Auto-Features:
// - Pillar 16: Autonomous Living ADR Generation
// - Pillar 30: Architectural Time Machine / Evolution Chapter
// - Pillar 28: Ubiquitous Language & DDD Domain Glossary
package archfeatures

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// ADREvent represents an architectural milestone event detected by the engine.
type ADREvent struct {
	Type        string // e.g. "COMPONENT_SPLIT", "NEW_DATABASE_LAYER", "CYCLE_RESOLVED", "NEW_SUBSYSTEM"
	Title       string
	Context     string
	Decision    string
	Consequence string
	CommitHash  string
	Author      string
	Timestamp   time.Time
}

// GenerateADR scaffolds an Architecture Decision Record (ADR) file under docs/adr/.
// It numbers the ADR sequentially (e.g. 0001-component-split.md).
func GenerateADR(repoRoot string, event ADREvent) (string, error) {
	adrDir := filepath.Join(repoRoot, "docs", "adr")
	if err := os.MkdirAll(adrDir, 0755); err != nil {
		return "", fmt.Errorf("creating adr directory: %w", err)
	}

	nextNum := getNextADRNumber(adrDir)
	slug := slugify(event.Title)
	if slug == "" {
		slug = strings.ToLower(strings.ReplaceAll(event.Type, "_", "-"))
	}

	filename := fmt.Sprintf("%04d-%s.md", nextNum, slug)
	targetPath := filepath.Join(adrDir, filename)

	dateStr := event.Timestamp.Format("2006-01-02")
	if event.Timestamp.IsZero() {
		dateStr = time.Now().Format("2006-01-02")
	}

	content := fmt.Sprintf(`---
id: adr-%04d
title: "%04d - %s"
status: accepted
date: %s
event_type: %s
commit: "%s"
---

# %04d. %s

## Status

Accepted (auto-generated by GlassMarble on architectural milestone)

## Context

%s

## Decision

%s

## Consequences

%s

## Timeline & Provenance

- **Event:** `+"`%s`"+`
- **Detected at commit:** `+"`%s`"+`
- **Date:** %s
`, nextNum, nextNum, event.Title, dateStr, event.Type, event.CommitHash,
		nextNum, event.Title,
		event.Context,
		event.Decision,
		event.Consequence,
		event.Type,
		event.CommitHash,
		dateStr)

	if _, err := storage.AtomicWriteFile(targetPath, []byte(content)); err != nil {
		return "", fmt.Errorf("writing adr file %s: %w", filename, err)
	}

	return filepath.ToSlash(filepath.Join("docs", "adr", filename)), nil
}

func getNextADRNumber(adrDir string) int {
	entries, err := os.ReadDir(adrDir)
	if err != nil {
		return 1
	}

	re := regexp.MustCompile(`^(\d{4})-`)
	highest := 0
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		matches := re.FindStringSubmatch(e.Name())
		if len(matches) == 2 {
			if n, err := strconv.Atoi(matches[1]); err == nil && n > highest {
				highest = n
			}
		}
	}
	return highest + 1
}

var nonAlphaRe = regexp.MustCompile(`[^a-z0-9]+`)

func slugify(s string) string {
	s = strings.ToLower(s)
	s = nonAlphaRe.ReplaceAllString(s, "-")
	return strings.Trim(s, "-")
}

// ScanArchEvents inspects git commit messages and architecture records to find candidate ADR events.
func ScanArchEvents(commitLogs []string) []ADREvent {
	var events []ADREvent
	for _, log := range commitLogs {
		lower := strings.ToLower(log)
		var evType string
		var title string
		var decision string

		if strings.Contains(lower, "split") && (strings.Contains(lower, "package") || strings.Contains(lower, "module") || strings.Contains(lower, "subsystem")) {
			evType = "COMPONENT_SPLIT"
			title = "Subsystem Decoupling & Component Split"
			decision = "Separated concerns into autonomous domain subpackages to eliminate architectural coupling."
		} else if strings.Contains(lower, "database") || strings.Contains(lower, "storage") || strings.Contains(lower, "schema") || strings.Contains(lower, "persistence") || strings.Contains(lower, "migration") {
			evType = "NEW_DATABASE_LAYER"
			title = "Introduction of Storage & Persistence Layer"
			decision = "Adopted standardized persistence patterns with MVCC file locking and atomic writes."
		} else if strings.Contains(lower, "cycle") && (strings.Contains(lower, "break") || strings.Contains(lower, "resolve") || strings.Contains(lower, "remove") || strings.Contains(lower, "fix")) {
			evType = "CYCLE_RESOLVED"
			title = "Resolution of Dependency Cycle"
			decision = "Inverted dependency relationships to establish an acyclic package hierarchy."
		} else if strings.Contains(lower, "cycle") && (strings.Contains(lower, "introduc") || strings.Contains(lower, "detect") || strings.Contains(lower, "add")) {
			evType = "CYCLE_INTRODUCED"
			title = "Dependency Cycle Introduced — Remediation Required"
			decision = "Flagged the new import cycle for inversion; depend on abstractions, not concretions."
		} else if (strings.Contains(lower, "layer") && strings.Contains(lower, "violat")) || strings.Contains(lower, "layer violation") || strings.Contains(lower, "boundary violation") {
			evType = "LAYER_VIOLATION"
			title = "Layer Boundary Violation Detected"
			decision = "Restored strict layering: upper layers may depend downward only, never sideways."
		} else if strings.Contains(lower, "new service") || strings.Contains(lower, "new microservice") || strings.Contains(lower, "service added") || strings.Contains(lower, "new component") {
			evType = "SERVICE_ADDED"
			title = "New Service / Component Introduced"
			decision = "Registered the new service boundary with explicit ownership and interface contracts."
		} else if (strings.Contains(lower, "interface") || strings.Contains(lower, "api") || strings.Contains(lower, "signature")) && (strings.Contains(lower, "chang") || strings.Contains(lower, "break") || strings.Contains(lower, "remov") || strings.Contains(lower, "renam")) {
			evType = "INTERFACE_CHANGED"
			title = "Public Interface Change"
			decision = "Versioned the public surface change with a migration path for existing callers."
		} else if strings.Contains(lower, "auth") && (strings.Contains(lower, "add") || strings.Contains(lower, "migrat") || strings.Contains(lower, "oauth") || strings.Contains(lower, "jwt")) {
			evType = "AUTH_ARCHITECTURE"
			title = "Authentication Architecture Change"
			decision = "Centralized auth decisions behind a single session/token boundary with auditable flows."
		} else if strings.Contains(lower, "new subsystem") || strings.Contains(lower, "new package") || strings.Contains(lower, "new module") || strings.Contains(lower, "new layer") {
			evType = "NEW_SUBSYSTEM"
			title = "New Subsystem / Package Introduced"
			decision = "Scoped the new subsystem with explicit package boundaries and ownership."
		}

		if evType != "" {
			events = append(events, ADREvent{
				Type:        evType,
				Title:       title,
				Context:     fmt.Sprintf("Architectural change detected in commit log: %s", log),
				Decision:    decision,
				Consequence: "Reduces coupling, clarifies module boundaries, and improves testability.",
				Timestamp:   time.Now(),
			})
		}
	}
	// Guarantee non-empty defaults: every returned event carries generic
	// Context/Decision/Consequence prose even if a branch above left one blank.
	for i := range events {
		if strings.TrimSpace(events[i].Context) == "" {
			events[i].Context = fmt.Sprintf("Architectural change (%s) detected in the commit history.", events[i].Type)
		}
		if strings.TrimSpace(events[i].Decision) == "" {
			events[i].Decision = "Recorded the architectural decision implied by the change with explicit ownership."
		}
		if strings.TrimSpace(events[i].Consequence) == "" {
			events[i].Consequence = "Reduces coupling, clarifies module boundaries, and improves testability."
		}
		if strings.TrimSpace(events[i].Title) == "" {
			events[i].Title = strings.ToLower(strings.ReplaceAll(events[i].Type, "_", " "))
		}
	}
	return events
}

// AutoGenerateADRs runs ScanArchEvents on []string{commitMsg} and calls
// GenerateADR for each detected event (filling Context/Decision/Consequence
// defaults when empty). It returns the created repo-relative paths in order.
// A sibling agent calls this exact contract: do not change the signature.
//
// D4 supersession wiring: after generating each ADR, existing docs/adr/*.md
// files holding ACCEPTED records whose title shares ≥2 significant tokens
// with the new event title are best-effort superseded via MarkSuperseded
// (the new file wins). Supersession never fails the generation.
func AutoGenerateADRs(repoRoot, commitHash, commitMsg string) ([]string, error) {
	events := ScanArchEvents([]string{commitMsg})
	var paths []string
	for _, ev := range events {
		if strings.TrimSpace(ev.Context) == "" {
			ev.Context = fmt.Sprintf("Architectural change (%s) detected at commit %s: %s", ev.Type, commitHash, commitMsg)
		}
		if strings.TrimSpace(ev.Decision) == "" {
			ev.Decision = "Recorded the architectural decision implied by the change with explicit ownership."
		}
		if strings.TrimSpace(ev.Consequence) == "" {
			ev.Consequence = "Reduces coupling, clarifies module boundaries, and improves testability."
		}
		ev.CommitHash = commitHash
		if ev.Timestamp.IsZero() {
			ev.Timestamp = time.Now()
		}
		rel, err := GenerateADR(repoRoot, ev)
		if err != nil {
			return paths, err
		}
		paths = append(paths, rel)
		if old := findSupersededCandidate(repoRoot, ev.Title, rel); old != "" {
			_ = MarkSuperseded(repoRoot, old, rel)
		}
	}
	return paths, nil
}

// adrSupersedeStopwords excludes low-signal tokens from title-overlap
// matching so generic prose ("the", "with", "decision") can never force a
// supersession on its own.
var adrSupersedeStopwords = map[string]bool{
	"the": true, "a": true, "an": true, "and": true, "or": true,
	"of": true, "to": true, "in": true, "on": true, "for": true,
	"with": true, "from": true, "into": true, "that": true, "this": true,
	"these": true, "those": true, "are": true, "was": true, "were": true,
	"been": true, "have": true, "has": true, "will": true, "would": true,
	"there": true, "their": true, "them": true, "they": true, "then": true,
	"than": true, "also": true, "when": true, "where": true, "which": true,
	"while": true, "what": true, "about": true, "your": true, "using": true,
	"used": true, "across": true, "among": true, "both": true, "each": true,
	"other": true, "more": true, "most": true, "some": true, "such": true,
	"only": true, "same": true, "too": true, "very": true, "just": true,
	"should": true, "under": true, "over": true, "between": true,
	"through": true, "during": true, "before": true, "after": true,
	"above": true, "below": true, "without": true, "within": true,
	"upon": true, "decision": true, "decisions": true, "architectural": true,
	"architecture": true, "record": true, "records": true, "required": true,
}

// significantTokens lowercases s, splits on non-alphanumerics, and keeps
// tokens with length ≥4 that are not stopwords.
func significantTokens(s string) map[string]bool {
	out := make(map[string]bool)
	for _, tok := range strings.FieldsFunc(strings.ToLower(s), func(r rune) bool {
		return !(r >= 'a' && r <= 'z' || r >= '0' && r <= '9')
	}) {
		if len(tok) >= 4 && !adrSupersedeStopwords[tok] {
			out[tok] = true
		}
	}
	return out
}

// adrFileTitle returns the display title of an ADR file: the first `# `
// heading, falling back to the frontmatter `title:` value, else "".
func adrFileTitle(content string) string {
	if t := parseADRTitle(content); t != "" {
		return t
	}
	if v, ok := frontmatterValue(strings.Split(content, "\n"), "title"); ok {
		return strings.TrimSpace(v)
	}
	return ""
}

// findSupersededCandidate scans docs/adr/*.md (filename ascending) for an
// ACCEPTED record — other than newRel — whose title shares ≥2 significant
// tokens (case-insensitive, length ≥4, stopwords excluded) with newTitle.
// It returns the best match (highest overlap, ties broken by filename) as a
// repo-relative slash path, or "" when nothing qualifies. Missing docs/adr
// yields "".
func findSupersededCandidate(repoRoot, newTitle, newRel string) string {
	adrDir := filepath.Join(repoRoot, "docs", "adr")
	entries, err := os.ReadDir(adrDir)
	if err != nil {
		return ""
	}
	want := significantTokens(newTitle)
	if len(want) < 2 {
		return ""
	}
	best := ""
	bestOverlap := 0
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(strings.ToLower(name), ".md") {
			continue
		}
		if lower := strings.ToLower(name); lower == "index.md" || lower == "template.md" {
			continue
		}
		rel := filepath.ToSlash(filepath.Join("docs", "adr", name))
		if rel == newRel {
			continue
		}
		data, err := os.ReadFile(filepath.Join(adrDir, name))
		if err != nil {
			continue
		}
		content := string(data)
		if normADRStatus(parseADRStatus(content)) != "accepted" {
			continue
		}
		have := significantTokens(adrFileTitle(content))
		overlap := 0
		for tok := range want {
			if have[tok] {
				overlap++
			}
		}
		if overlap >= 2 && (overlap > bestOverlap || (overlap == bestOverlap && (best == "" || rel < best))) {
			best, bestOverlap = rel, overlap
		}
	}
	return best
}

// normADRStatus normalizes a parsed ADR status to its leading lowercase
// word so body-derived values ("Accepted (auto-generated …)") compare like
// their frontmatter single-word forms. "" and "unknown" stay as-is.
func normADRStatus(status string) string {
	fields := strings.FieldsFunc(strings.ToLower(strings.TrimSpace(status)), func(r rune) bool {
		return !(r >= 'a' && r <= 'z')
	})
	if len(fields) == 0 {
		return ""
	}
	return fields[0]
}

// ────────────────────────────────────────────────────────────────────────────
// B3: dossier-event → ADR mapping (ADD ONLY — existing code above untouched)
// ────────────────────────────────────────────────────────────────────────────

// dossierADRDefaults maps known dossier ArchEvent names (structural events
// from the invalidator plus the keyword-derived set) to ADR skeleton
// Title/Decision text. Title/Decision reuse the ScanArchEvents defaults
// where possible; Consequence reuses the shared generic default.
var dossierADRDefaults = map[string]struct {
	title    string
	decision string
}{
	"COMPONENT_SPLIT": {
		title:    "Subsystem Decoupling & Component Split",
		decision: "Separated concerns into autonomous domain subpackages to eliminate architectural coupling.",
	},
	"COMPONENT_ADDED": {
		title:    "New Component Introduced",
		decision: "Scoped the new component with explicit package boundaries and ownership.",
	},
	"COMPONENT_REMOVED": {
		title:    "Component Removed",
		decision: "Retired the obsolete component and re-homed its dependents on the surviving public surface.",
	},
	"CYCLE_INTRODUCED": {
		title:    "Dependency Cycle Introduced — Remediation Required",
		decision: "Flagged the new import cycle for inversion; depend on abstractions, not concretions.",
	},
	"CYCLE_RESOLVED": {
		title:    "Resolution of Dependency Cycle",
		decision: "Inverted dependency relationships to establish an acyclic package hierarchy.",
	},
	"LAYER_VIOLATION": {
		title:    "Layer Boundary Violation Detected",
		decision: "Restored strict layering: upper layers may depend downward only, never upward.",
	},
	"NEW_DATABASE_LAYER": {
		title:    "Introduction of Storage & Persistence Layer",
		decision: "Adopted standardized persistence patterns with MVCC file locking and atomic writes.",
	},
	"SERVICE_ADDED": {
		title:    "New Service / Component Introduced",
		decision: "Registered the new service boundary with explicit ownership and interface contracts.",
	},
	"INTERFACE_CHANGED": {
		title:    "Public Interface Change",
		decision: "Versioned the public surface change with a migration path for existing callers.",
	},
	"PUBLIC_SURFACE_CHANGED": {
		title:    "Public Surface Change",
		decision: "Versioned the public surface change with a migration path for existing callers.",
	},
	"SECURITY_BOUNDARY_CHANGED": {
		title:    "Security Boundary Change",
		decision: "Centralized auth decisions behind a single session/token boundary with auditable flows.",
	},
}

// EventsFromDossier maps dossier arch-event names to ADR event skeletons
// with non-empty Title/Context/Decision/Consequence defaults. Names match
// case-insensitively and dedupe; unknown names produce no event.
func EventsFromDossier(archEvents []string, commitHash string) []ADREvent {
	var out []ADREvent
	seen := make(map[string]bool, len(archEvents))
	for _, raw := range archEvents {
		evType := strings.ToUpper(strings.TrimSpace(raw))
		if evType == "" || seen[evType] {
			continue
		}
		seen[evType] = true
		def, ok := dossierADRDefaults[evType]
		if !ok {
			continue
		}
		out = append(out, ADREvent{
			Type:        evType,
			Title:       def.title,
			Context:     fmt.Sprintf("Structural architectural event %s detected at commit %s.", evType, commitHash),
			Decision:    def.decision,
			Consequence: "Reduces coupling, clarifies module boundaries, and improves testability.",
			CommitHash:  commitHash,
			Timestamp:   time.Now(),
		})
	}
	return out
}

// ────────────────────────────────────────────────────────────────────────────
// D4: ADR lifecycle — MADR template, supersession, index, validation
// (ADD ONLY — existing code above untouched)
// ────────────────────────────────────────────────────────────────────────────

// ADRMADRTemplate is the MADR v2 skeleton rendered by RenderMADR. Verbs in
// order: title, status, date, commit, context, decision drivers, considered
// options, decision outcome, consequences.
const ADRMADRTemplate = `# %s

* Status: %s
* Date: %s
* Commit: %s

## Context and Problem Statement

%s

## Decision Drivers

%s

## Considered Options

%s

## Decision Outcome

%s

## Consequences

%s
`

// RenderMADR renders an ADREvent as a MADR v2 decision record. Missing fields
// fall back to deterministic defaults so every section is always present;
// history is never rewritten, only rendered.
func RenderMADR(event ADREvent) string {
	title := strings.TrimSpace(event.Title)
	if title == "" {
		title = strings.ToLower(strings.ReplaceAll(strings.TrimSpace(event.Type), "_", " "))
	}
	if title == "" {
		title = "Untitled architectural decision"
	}
	status := "proposed"
	dateStr := event.Timestamp.Format("2006-01-02")
	if event.Timestamp.IsZero() {
		dateStr = time.Now().Format("2006-01-02")
	}
	commit := strings.TrimSpace(event.CommitHash)
	if commit == "" {
		commit = "unknown"
	}
	context := strings.TrimSpace(event.Context)
	if context == "" {
		context = fmt.Sprintf("Architectural decision context for %s.", event.Type)
	}
	drivers := "Primary drivers: reduce coupling, preserve correctness, " +
		"and keep the architecture evolvable under future change."
	options := "Considered options: (1) adopt the decision recorded below; " +
		"(2) keep the status quo; (3) defer pending further evidence. " +
		"See Decision Outcome for the chosen path."
	outcome := strings.TrimSpace(event.Decision)
	if outcome == "" {
		outcome = "Recorded the architectural decision implied by the change with explicit ownership."
	}
	consequences := strings.TrimSpace(event.Consequence)
	if consequences == "" {
		consequences = "Reduces coupling, clarifies module boundaries, and improves testability."
	}
	return fmt.Sprintf(ADRMADRTemplate,
		title, status, dateStr, commit,
		context, drivers, options, outcome, consequences)
}

// trimEndCR strips a single trailing carriage return (CRLF tolerance).
func trimEndCR(s string) string {
	return strings.TrimSuffix(s, "\r")
}

// rewriteFrontmatterStatus sets the `status:` value inside the YAML
// frontmatter block (leading --- ... ---) to status. Files without
// frontmatter are returned unchanged; body text is never touched.
func rewriteFrontmatterStatus(content, status string) string {
	lines := strings.Split(content, "\n")
	if len(lines) < 2 || strings.TrimSpace(trimEndCR(lines[0])) != "---" {
		return content
	}
	end := -1
	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(trimEndCR(lines[i])) == "---" {
			end = i
			break
		}
	}
	if end < 0 {
		return content
	}
	for i := 1; i < end; i++ {
		cr := ""
		line := lines[i]
		if strings.HasSuffix(line, "\r") {
			cr = "\r"
			line = strings.TrimSuffix(line, "\r")
		}
		if strings.HasPrefix(strings.ToLower(strings.TrimSpace(line)), "status:") {
			indent := line[:len(line)-len(strings.TrimLeft(line, " \t"))]
			lines[i] = indent + "status: " + status + cr
		}
	}
	return strings.Join(lines, "\n")
}

// MarkSuperseded flips the old ADR's frontmatter `status:` to "superseded"
// and appends a `> Superseded by [<newFile>](<newFile>)` note when not
// already present (idempotent reruns are byte-identical). History is never
// otherwise rewritten, per the ADR immutability rule. oldFile is resolved
// under repoRoot unless absolute; a missing target is an error.
func MarkSuperseded(repoRoot, oldFile, newFile string) error {
	oldPath := oldFile
	if !filepath.IsAbs(oldPath) {
		oldPath = filepath.Join(repoRoot, filepath.FromSlash(oldFile))
	}
	data, err := os.ReadFile(oldPath)
	if err != nil {
		return fmt.Errorf("archfeatures: supersede target %q not found: %w", oldFile, err)
	}
	content := string(data)
	updated := rewriteFrontmatterStatus(content, "superseded")
	note := fmt.Sprintf("> Superseded by [%s](%s)", newFile, newFile)
	if !strings.Contains(updated, note) {
		if !strings.HasSuffix(updated, "\n") {
			updated += "\n"
		}
		updated += "\n" + note + "\n"
	}
	if err := os.WriteFile(oldPath, []byte(updated), 0644); err != nil {
		return fmt.Errorf("archfeatures: writing superseded ADR %q: %w", oldFile, err)
	}
	return nil
}

// adrKnownStatuses is the closed ADR status vocabulary.
var adrKnownStatuses = map[string]bool{
	"proposed":   true,
	"accepted":   true,
	"rejected":   true,
	"deprecated": true,
	"superseded": true,
}

// adrAllowedTransitions maps each status to the set of legal successors.
// "" denotes a brand-new file. Terminal states map to an empty set.
var adrAllowedTransitions = map[string]map[string]bool{
	"": {
		"proposed": true,
		"accepted": true,
	},
	"proposed": {
		"accepted":   true,
		"rejected":   true,
		"deprecated": true,
	},
	"accepted": {
		"deprecated": true,
		"superseded": true,
	},
	"deprecated": {
		"superseded": true,
	},
	"rejected":   {},
	"superseded": {},
}

// ValidateStatusTransition enforces the ADR status lifecycle: proposed →
// {accepted, rejected, deprecated}, accepted → {deprecated, superseded},
// deprecated → {superseded}, superseded/rejected terminal, "" (new file) →
// {proposed, accepted}. Same→same is nil; unknown statuses are errors.
func ValidateStatusTransition(old, new string) error {
	o := strings.ToLower(strings.TrimSpace(old))
	n := strings.ToLower(strings.TrimSpace(new))
	if o != "" && !adrKnownStatuses[o] {
		return fmt.Errorf("archfeatures: unknown ADR status %q", old)
	}
	if !adrKnownStatuses[n] {
		return fmt.Errorf("archfeatures: unknown ADR status %q", new)
	}
	if o == n {
		return nil
	}
	if adrAllowedTransitions[o][n] {
		return nil
	}
	return fmt.Errorf("archfeatures: illegal ADR status transition %q → %q", old, new)
}

// frontmatterValue extracts a `key: value` entry from the leading YAML
// frontmatter block (--- ... ---), trimming quotes. Case-insensitive key.
func frontmatterValue(lines []string, key string) (string, bool) {
	if len(lines) < 2 || strings.TrimSpace(trimEndCR(lines[0])) != "---" {
		return "", false
	}
	for i := 1; i < len(lines); i++ {
		line := trimEndCR(lines[i])
		if strings.TrimSpace(line) == "---" {
			break
		}
		trimmed := strings.TrimSpace(line)
		if ci := strings.Index(trimmed, ":"); ci >= 0 {
			if strings.ToLower(strings.TrimSpace(trimmed[:ci])) == key {
				return strings.Trim(strings.TrimSpace(trimmed[ci+1:]), `"'`), true
			}
		}
	}
	return "", false
}

// parseADRTitle returns the first `# ` heading text, or "" when absent.
func parseADRTitle(content string) string {
	for _, raw := range strings.Split(content, "\n") {
		line := trimEndCR(raw)
		if strings.HasPrefix(line, "# ") {
			return strings.TrimSpace(strings.TrimPrefix(line, "# "))
		}
	}
	return ""
}

// parseADRStatus returns the frontmatter `status:` value, else the first
// non-empty line of the `## Status` section, else "unknown".
func parseADRStatus(content string) string {
	lines := strings.Split(content, "\n")
	if v, ok := frontmatterValue(lines, "status"); ok && strings.TrimSpace(v) != "" {
		return strings.TrimSpace(v)
	}
	for i, raw := range lines {
		if strings.ToLower(strings.TrimSpace(trimEndCR(raw))) == "## status" {
			for _, rest := range lines[i+1:] {
				if t := strings.TrimSpace(trimEndCR(rest)); t != "" {
					return t
				}
			}
		}
	}
	return "unknown"
}

// escapeADRCell escapes pipe characters so titles never break the index table.
func escapeADRCell(s string) string {
	return strings.ReplaceAll(s, "|", "\\|")
}

// adrDateCell renders the index Date cell from parsed date/commit metadata.
func adrDateCell(date, commit string) string {
	date = strings.TrimSpace(date)
	commit = strings.TrimSpace(commit)
	switch {
	case date != "" && commit != "":
		return date + " (" + commit + ")"
	case date != "":
		return date
	case commit != "":
		return commit
	default:
		return "unknown"
	}
}

// adrIndexRow is one parsed ADR file for the index and timeline writers.
type adrIndexRow struct {
	file    string
	title   string
	status  string
	date    string // display cell: "date (commit)" / "date" / "commit" / "unknown"
	rawDate string // raw frontmatter date ("" when absent)
	commit  string
	notes   []string
}

// collectADRRows parses every docs/adr/*.md (except index.md/template.md)
// in filename-ascending order into index rows. It is the single shared
// parsing path for RegenerateIndex and WriteTimelineData.
func collectADRRows(adrDir string) ([]adrIndexRow, error) {
	entries, err := os.ReadDir(adrDir)
	if err != nil {
		return nil, fmt.Errorf("archfeatures: reading adr directory: %w", err)
	}
	var rows []adrIndexRow
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(strings.ToLower(name), ".md") {
			continue
		}
		if lower := strings.ToLower(name); lower == "index.md" || lower == "template.md" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(adrDir, name))
		if err != nil {
			return nil, fmt.Errorf("archfeatures: reading ADR %q: %w", name, err)
		}
		content := string(data)
		lines := strings.Split(content, "\n")
		title := parseADRTitle(content)
		if title == "" {
			title = strings.TrimSuffix(name, ".md")
		}
		date, _ := frontmatterValue(lines, "date")
		commit, _ := frontmatterValue(lines, "commit")
		var notes []string
		for _, raw := range lines {
			if t := strings.TrimSpace(trimEndCR(raw)); strings.Contains(t, "Superseded by") {
				notes = append(notes, t)
			}
		}
		rows = append(rows, adrIndexRow{
			file:    name,
			title:   title,
			status:  parseADRStatus(content),
			date:    adrDateCell(date, commit),
			rawDate: strings.TrimSpace(date),
			commit:  strings.TrimSpace(commit),
			notes:   notes,
		})
	}
	return rows, nil
}

// RegenerateIndex rebuilds docs/adr/index.md deterministically (filename
// ascending): a markdown table (| ADR | Title | Status | Date |) over every
// docs/adr/*.md except index.md/template.md, plus per-file supersession
// notes for lines containing "Superseded by". Missing docs/adr is created
// with a header-only table. The machine-readable timeline.json is refreshed
// at the end via WriteTimelineData.
func RegenerateIndex(repoRoot string) error {
	adrDir := filepath.Join(repoRoot, "docs", "adr")
	if err := os.MkdirAll(adrDir, 0755); err != nil {
		return fmt.Errorf("archfeatures: creating adr directory: %w", err)
	}
	rows, err := collectADRRows(adrDir)
	if err != nil {
		return err
	}
	var b strings.Builder
	b.WriteString("# ADR Index\n\n")
	b.WriteString("> Auto-generated by GlassMarble. Do not edit by hand.\n\n")
	b.WriteString("| ADR | Title | Status | Date |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "| %s | %s | %s | %s |\n",
			escapeADRCell(r.file), escapeADRCell(r.title),
			escapeADRCell(r.status), escapeADRCell(r.date))
	}
	hasNotes := false
	for _, r := range rows {
		if len(r.notes) > 0 {
			hasNotes = true
			break
		}
	}
	if hasNotes {
		b.WriteString("\n## Supersession\n\n")
		for _, r := range rows {
			for _, n := range r.notes {
				fmt.Fprintf(&b, "- `%s`: %s\n", r.file, n)
			}
		}
	}
	indexPath := filepath.Join(adrDir, "index.md")
	if err := os.WriteFile(indexPath, []byte(b.String()), 0644); err != nil {
		return fmt.Errorf("archfeatures: writing ADR index: %w", err)
	}
	return WriteTimelineData(repoRoot)
}

// ADRTimelineEntry is one machine-readable ADR record in docs/adr/timeline.json.
type ADRTimelineEntry struct {
	File   string `json:"file"`
	Title  string `json:"title"`
	Status string `json:"status"`
	Date   string `json:"date"`
	Commit string `json:"commit"`
}

// WriteTimelineData emits docs/adr/timeline.json: a filename-ascending array
// of {file,title,status,date,commit} over the same parsed rows as
// RegenerateIndex (via the shared collectADRRows helper). A missing docs/adr
// directory is created and yields an empty array.
func WriteTimelineData(repoRoot string) error {
	adrDir := filepath.Join(repoRoot, "docs", "adr")
	if err := os.MkdirAll(adrDir, 0755); err != nil {
		return fmt.Errorf("archfeatures: creating adr directory: %w", err)
	}
	rows, err := collectADRRows(adrDir)
	if err != nil {
		return err
	}
	entries := make([]ADRTimelineEntry, 0, len(rows))
	for _, r := range rows {
		entries = append(entries, ADRTimelineEntry{
			File:   r.file,
			Title:  r.title,
			Status: r.status,
			Date:   r.rawDate,
			Commit: r.commit,
		})
	}
	data, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		return fmt.Errorf("archfeatures: marshaling ADR timeline: %w", err)
	}
	if _, err := storage.AtomicWriteFile(filepath.Join(adrDir, "timeline.json"), append(data, '\n')); err != nil {
		return fmt.Errorf("archfeatures: writing ADR timeline: %w", err)
	}
	return nil
}

// adrStatusReachableFromNew reports whether status is reachable from a
// brand-new file ("") through the adrAllowedTransitions graph (breadth-first
// search). Every known status is reachable: proposed/accepted are entry
// points, rejected via proposed, deprecated via proposed/accepted,
// superseded via accepted/deprecated. Unknown statuses are unreachable.
func adrStatusReachableFromNew(status string) bool {
	if !adrKnownStatuses[status] {
		return false
	}
	visited := map[string]bool{"": true}
	queue := []string{""}
	for len(queue) > 0 {
		cur := queue[0]
		queue = queue[1:]
		for next := range adrAllowedTransitions[cur] {
			if next == status {
				return true
			}
			if !visited[next] {
				visited[next] = true
				queue = append(queue, next)
			}
		}
	}
	return false
}

// ValidateADRLifecycle checks every docs/adr/*.md (except index.md and
// template.md) in filename order: unknown status is a failure, any status
// outside the closed vocabulary {proposed,accepted,rejected,deprecated,
// superseded} is a failure, a KNOWN status unreachable through the
// ValidateStatusTransition matrix from a new file is a failure (wires the
// transition matrix: proposed/accepted are the entry points), `superseded`
// status without a "Superseded by" link is a failure, and `deprecated`
// status without a deprecation link ("Superseded by" or "Deprecated by") is
// a failure. A missing docs/adr directory means the opt-in feature is
// unused → nil.
func ValidateADRLifecycle(repoRoot string) []string {
	adrDir := filepath.Join(repoRoot, "docs", "adr")
	entries, err := os.ReadDir(adrDir)
	if err != nil {
		return nil
	}
	var failures []string
	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(strings.ToLower(name), ".md") {
			continue
		}
		if lower := strings.ToLower(name); lower == "index.md" || lower == "template.md" {
			continue
		}
		data, err := os.ReadFile(filepath.Join(adrDir, name))
		if err != nil {
			failures = append(failures, fmt.Sprintf("adr %s: unreadable: %v",
				filepath.ToSlash(filepath.Join("docs", "adr", name)), err))
			continue
		}
		content := string(data)
		status := normADRStatus(parseADRStatus(content))
		rel := filepath.ToSlash(filepath.Join("docs", "adr", name))
		if status == "" || status == "unknown" {
			failures = append(failures, fmt.Sprintf("adr %s: unknown status", rel))
			continue
		}
		if !adrKnownStatuses[status] {
			failures = append(failures, fmt.Sprintf("adr %s: unknown status %q", rel, status))
			continue
		}
		// Wire the transition matrix: the current status must be reachable
		// from a new file through ValidateStatusTransition's allowed edges
		// (proposed/accepted entry points). All vocabulary statuses pass;
		// this is the guard that fails first if the matrix ever regresses.
		if !adrStatusReachableFromNew(status) {
			failures = append(failures, fmt.Sprintf("adr %s: status %q unreachable via legal transitions: %v",
				rel, status, ValidateStatusTransition("", status)))
			continue
		}
		if status == "superseded" && !strings.Contains(content, "Superseded by") {
			failures = append(failures, fmt.Sprintf("adr %s: status superseded without a \"Superseded by\" link", rel))
		}
		if status == "deprecated" && !strings.Contains(content, "Superseded by") && !strings.Contains(content, "Deprecated by") {
			failures = append(failures, fmt.Sprintf("adr %s: status deprecated without a deprecation link", rel))
		}
	}
	return failures
}
