package archfeatures

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// DomainTerm represents a DDD entity, value object, or ubiquitous language term.
type DomainTerm struct {
	Name           string
	BoundedContext string
	Package        string
	Kind           string // Entity, ValueObject, Interface, Service
	DocComment     string
	SourcePath     string
	Line           int
}

// GenerateDomainGlossary scans the repository for domain model definitions,
// identifies terminology collisions across bounded contexts, and generates docs/glossary.md.
func GenerateDomainGlossary(repoRoot string) (string, error) {
	terms, err := collectDomainTerms(repoRoot)
	if err != nil {
		return "", err
	}

	// Detect homonyms / cross-context collisions
	byName := make(map[string][]DomainTerm)
	for _, t := range terms {
		byName[t.Name] = append(byName[t.Name], t)
	}

	var sb strings.Builder
	sb.WriteString("# Ubiquitous Language & Domain Glossary\n\n")
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 28).\n")
	sb.WriteString("> Catalogs domain entities, value objects, and detects terminology collisions across bounded contexts.\n\n")

	// Section 1: Terminology Conflicts
	var conflicts []string
	for name, group := range byName {
		if len(group) > 1 {
			contexts := make(map[string]bool)
			for _, item := range group {
				contexts[item.BoundedContext] = true
			}
			if len(contexts) > 1 {
				conflicts = append(conflicts, name)
			}
		}
	}
	sort.Strings(conflicts)

	if len(conflicts) > 0 {
		sb.WriteString("## Cross-Context Terminology Collisions\n\n")
		sb.WriteString("| Term | Bounded Contexts | Definitions & Permalinks |\n")
		sb.WriteString("| :--- | :--- | :--- |\n")
		for _, name := range conflicts {
			items := byName[name]
			var ctxList []string
			var links []string
			for _, item := range items {
				ctxList = append(ctxList, fmt.Sprintf("`%s`", item.BoundedContext))
				links = append(links, fmt.Sprintf("[%s:%d](%s#L%d)", item.Package, item.Line, item.SourcePath, item.Line))
			}
			sb.WriteString(fmt.Sprintf("| **%s** | %s | %s |\n", name, strings.Join(ctxList, ", "), strings.Join(links, "<br>")))
		}
		sb.WriteString("\n")
	}

	// Section 2: Complete Alphabetical Glossary
	sb.WriteString("## Glossary\n\n")
	sb.WriteString("| Term | Bounded Context | Kind | Description | Source |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- | :--- |\n")

	sort.Slice(terms, func(i, j int) bool {
		if terms[i].Name == terms[j].Name {
			return terms[i].BoundedContext < terms[j].BoundedContext
		}
		return terms[i].Name < terms[j].Name
	})

	for _, t := range terms {
		desc := t.DocComment
		if desc == "" {
			desc = fmt.Sprintf("Domain %s in %s", strings.ToLower(t.Kind), t.BoundedContext)
		}
		// sanitize markdown pipes and newlines
		desc = strings.ReplaceAll(desc, "|", "\\|")
		desc = strings.ReplaceAll(desc, "\n", " ")

		sb.WriteString(fmt.Sprintf("| **%s** | `%s` | %s | %s | [%s:%d](%s#L%d) |\n",
			t.Name, t.BoundedContext, t.Kind, desc, filepath.Base(t.SourcePath), t.Line, t.SourcePath, t.Line))
	}

	outPath := filepath.Join(repoRoot, "docs", "glossary.md")
	result := sb.String()
	_, err = storage.AtomicWriteFile(outPath, []byte(result))
	return result, err
}

func collectDomainTerms(repoRoot string) ([]DomainTerm, error) {
	var terms []DomainTerm
	fset := token.NewFileSet()

	err := filepath.WalkDir(repoRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == ".glassmarble" || name == "vendor" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		relPath, _ := filepath.Rel(repoRoot, path)
		relPath = filepath.ToSlash(relPath)

		// Context derived from directory e.g. internal/doc_engine -> doc_engine
		parts := strings.Split(relPath, "/")
		context := "root"
		if len(parts) >= 2 {
			context = parts[len(parts)-2]
		}

		node, parseErr := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if parseErr != nil {
			return nil
		}

		for _, decl := range node.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			docText := strings.TrimSpace(genDecl.Doc.Text())
			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok || !ast.IsExported(typeSpec.Name.Name) {
					continue
				}

				name := typeSpec.Name.Name
				kind := "Entity"
				if _, ok := typeSpec.Type.(*ast.InterfaceType); ok {
					kind = "Interface"
				} else if strings.HasSuffix(name, "Service") || strings.HasSuffix(name, "Manager") || strings.HasSuffix(name, "Engine") {
					kind = "Service"
				} else if strings.HasSuffix(name, "ID") || strings.HasSuffix(name, "State") || strings.HasSuffix(name, "Spec") {
					kind = "ValueObject"
				}

				pos := fset.Position(typeSpec.Pos())
				comment := docText
				if comment == "" && typeSpec.Doc != nil {
					comment = strings.TrimSpace(typeSpec.Doc.Text())
				}

				terms = append(terms, DomainTerm{
					Name:           name,
					BoundedContext: context,
					Package:        node.Name.Name,
					Kind:           kind,
					DocComment:     comment,
					SourcePath:     relPath,
					Line:           pos.Line,
				})
			}
		}
		return nil
	})

	return terms, err
}
