// Command man generates roff man pages for gmb and its subcommands.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/Syamchand123/GlassMarble/cmd"
	"github.com/Syamchand123/GlassMarble/internal/product"
	"github.com/spf13/cobra/doc"
)

func main() {
	outDir := flag.String("o", filepath.Join("docs", "man"), "Output directory for man pages")
	check := flag.Bool("check", false, "Verify the committed pages match the current command tree instead of writing them")
	flag.Parse()

	header := &doc.GenManHeader{
		Title:   "GMB",
		Section: "1",
		Date:    buildDate(),
		Source:  "GlassMarble " + product.Version,
		Manual:  "GlassMarble Manual",
	}

	if *check {
		os.Exit(runCheck(*outDir, header))
	}

	if err := os.MkdirAll(*outDir, 0755); err != nil {
		fmt.Fprintf(os.Stderr, "Error creating directory %s: %v\n", *outDir, err)
		os.Exit(1)
	}

	if err := doc.GenManTree(cmd.RootCmd(), header, *outDir); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating man pages: %v\n", err)
		os.Exit(1)
	}

	files, _ := filepath.Glob(filepath.Join(*outDir, "*.1"))
	fmt.Printf("Generated %d man page(s) into %s\n", len(files), *outDir)
}

// buildDate resolves the .TH date stamp. SOURCE_DATE_EPOCH (the
// reproducible-builds convention) wins so release pipelines can pin it;
// otherwise cobra's own default of "now" applies.
func buildDate() *time.Time {
	epoch := os.Getenv("SOURCE_DATE_EPOCH")
	if epoch == "" {
		return nil
	}
	secs, err := strconv.ParseInt(epoch, 10, 64)
	if err != nil {
		return nil
	}
	t := time.Unix(secs, 0).UTC()
	return &t
}

// runCheck regenerates the tree into a scratch directory and compares it with
// what is committed under outDir, so CI fails when a command gains a flag or
// changes its help text without the pages being regenerated. It returns the
// process exit code.
//
// The .TH line is excluded from the comparison: it carries only the build
// stamp (date and product.Version), which legitimately differs between a
// developer checkout and a tagged release and would otherwise report every
// run as stale.
func runCheck(outDir string, header *doc.GenManHeader) int {
	tmpDir, err := os.MkdirTemp("", "gmb-man-check-*")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating temp directory: %v\n", err)
		return 1
	}
	defer os.RemoveAll(tmpDir)

	if err := doc.GenManTree(cmd.RootCmd(), header, tmpDir); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating man pages: %v\n", err)
		return 1
	}

	want, err := readPages(tmpDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading generated pages: %v\n", err)
		return 1
	}
	got, err := readPages(outDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading %s: %v\n", outDir, err)
		return 1
	}

	var problems []string
	for name, body := range want {
		switch existing, ok := got[name]; {
		case !ok:
			problems = append(problems, "missing:   "+name)
		case existing != body:
			problems = append(problems, "stale:     "+name)
		}
	}
	for name := range got {
		if _, ok := want[name]; !ok {
			problems = append(problems, "orphaned:  "+name)
		}
	}

	if len(problems) > 0 {
		sort.Strings(problems)
		fmt.Fprintf(os.Stderr, "%s is out of date with the command tree:\n", outDir)
		for _, p := range problems {
			fmt.Fprintf(os.Stderr, "  %s\n", p)
		}
		fmt.Fprintf(os.Stderr, "Regenerate with: go run ./cmd/man -o %s\n", outDir)
		return 1
	}

	fmt.Printf("%s is up to date (%d man page(s))\n", outDir, len(want))
	return 0
}

// readPages loads every *.1 file in dir keyed by base name, with the .TH build
// stamp stripped so only command content is compared.
// isManBuildStamp reports whether a line carries only the date the pages were
// generated, which differs between any two runs on different days and says
// nothing about whether the command tree changed.
//
// Cobra stamps the date twice, and excluding just the .TH header was not
// enough: the SH HISTORY footer carries it at day granularity ("3-Sep-2026
// Auto generated by spf13/cobra") while .TH carries it by month, so every
// page compared unequal the day after it was generated and -check reported
// the whole tree stale.
func isManBuildStamp(line string) bool {
	return strings.HasPrefix(line, ".TH ") ||
		strings.HasSuffix(line, "Auto generated by spf13/cobra")
}

func readPages(dir string) (map[string]string, error) {
	paths, err := filepath.Glob(filepath.Join(dir, "*.1"))
	if err != nil {
		return nil, err
	}
	pages := make(map[string]string, len(paths))
	for _, p := range paths {
		data, err := os.ReadFile(p)
		if err != nil {
			return nil, err
		}
		var kept [][]byte
		for _, line := range bytes.Split(data, []byte("\n")) {
			// Trim the CR so the comparison behaves the same whether the
			// committed pages were checked out with LF or CRLF endings.
			text := strings.TrimRight(string(line), "\r")
			if isManBuildStamp(text) {
				continue
			}
			kept = append(kept, []byte(text))
		}
		pages[filepath.Base(p)] = string(bytes.Join(kept, []byte("\n")))
	}
	return pages, nil
}
