package edgecases_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Syamchand123/GlassMarble/tests/harness"
)

// TestEdgeEmptyPolyglotRepo verifies that analyze on an empty repo
// (no source files, only polyglot fixtures hidden) still produces a valid
// empty AKG and doctor passes.
func TestEdgeEmptyPolyglotRepo(t *testing.T) {
	sb := harness.NewSandbox(t)
	sb.GitInit()
	out, err := harness.RunGmb(t, sb, "analyze")
	if err != nil {
		t.Fatalf("analyze empty: %v\n%s", err, out)
	}
	if !strings.Contains(out, "Analyzed 0 files") && !strings.Contains(out, "Analyzed") {
		t.Errorf("empty analyze output unexpected: %s", out)
	}
	docOut, err := harness.RunGmb(t, sb, "doctor")
	if err != nil {
		t.Fatalf("doctor empty: %v\n%s", err, docOut)
	}
	if !strings.Contains(docOut, "DOCTOR") {
		t.Errorf("doctor output missing header: %s", docOut)
	}
}

// TestEdgeNoGitWithPolyglot ensures that projects without git still
// analyze correctly (fallback to full scan).
func TestEdgeNoGitWithPolyglot(t *testing.T) {
	sb := harness.NewSandbox(t)
	sb.PolyglotProject()
	// Do NOT call GitInit
	out, err := harness.RunGmb(t, sb, "analyze")
	if err != nil {
		t.Fatalf("analyze no-git polyglot: %v\n%s", err, out)
	}
	if !strings.Contains(out, "Analyzed") {
		t.Errorf("no-git analyze missing Analyzed: %s", out)
	}
}

// TestEdgeBinaryAndLargeFiles verifies that binary and oversized files are
// skipped gracefully and do not crash the pipeline.
func TestEdgeBinaryAndLargeFiles(t *testing.T) {
	sb := harness.NewSandbox(t)
	sb.SampleProject()
	// Add binary file
	binPath := sb.Path("assets/image.png")
	_ = os.MkdirAll(filepath.Dir(binPath), 0o755)
	_ = os.WriteFile(binPath, []byte{0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A}, 0o644)
	// Add just-over-threshold large file (5MB)
	sb.WriteFile("data/large.bin", strings.Repeat("x", 5<<20))
	out, err := harness.RunGmb(t, sb, "analyze")
	if err != nil {
		t.Fatalf("analyze with binary/large: %v\n%s", err, out)
	}
	if !strings.Contains(out, "Analyzed") {
		t.Errorf("analyze with binary files missing Analyzed: %s", out)
	}
	// Ensure warning about skipped files appears
	if !strings.Contains(out, "skipped") && !strings.Contains(out, "warn") {
		t.Logf("no explicit skipped warning (informational): %s", out)
	}
}

// TestEdgeHiddenVendorGenerated ensures that hidden directories, vendor,
// and generated files are excluded even in polyglot mode.
func TestEdgeHiddenVendorGenerated(t *testing.T) {
	sb := harness.NewSandbox(t)
	sb.PolyglotProject()
	sb.WriteFile(".hidden/secret.go", `package hidden; func Secret() {}`)
	sb.WriteFile("vendor/github.com/foo/bar.go", `package foo; func Bar() {}`)
	sb.WriteFile("api/gen.pb.go", `// Code generated by protoc-gen-go. DO NOT EDIT.
package api; func Init() {}`)
	sb.GitInit()
	out, err := harness.RunGmb(t, sb, "analyze")
	if err != nil {
		t.Fatalf("analyze hidden/vendor: %v\n%s", err, out)
	}
	// Inspect should not list symbols from excluded files
	inspectOut, err := harness.RunGmb(t, sb, "inspect", "--list")
	if err != nil {
		t.Logf("inspect failed (may be empty): %v\n%s", err, inspectOut)
	}
	if strings.Contains(inspectOut, "Secret") || strings.Contains(inspectOut, "Bar") {
		t.Errorf("excluded files leaked into inspect: %s", inspectOut)
	}
}

// TestEdgeVisualizationEmptyGraph ensures that visualizing an empty
// graph does not panic and produces a placeholder or a clear empty-subgraph error.
func TestEdgeVisualizationEmptyGraph(t *testing.T) {
	sb := harness.NewSandbox(t)
	sb.GitInit()
	harness.RunGmb(t, sb, "analyze")
	for _, d := range []string{"class", "dependency", "flowchart"} {
		out, err := harness.RunGmb(t, sb, "visualize", d)
		if err != nil {
			// Empty graph is expected to error with empty subgraph message
			if !strings.Contains(out, "empty subgraph") && !strings.Contains(err.Error(), "empty") {
				t.Errorf("visualize %s on empty graph failed unexpectedly: %v\n%s", d, err, out)
			}
			continue
		}
		if strings.TrimSpace(out) == "" {
			t.Errorf("visualize %s empty on empty graph", d)
		}
	}
}
