.nh
.TH "GMB" "1" "Aug 2026" "GlassMarble 0.1.0" "GlassMarble Manual"

.SH NAME
gmb-completion - Generate shell completion scripts


.SH SYNOPSIS
\fBgmb completion [bash|zsh|fish|powershell] [flags]\fP


.SH DESCRIPTION
Generate shell completion script for gmb:
  Bash:       source <(gmb completion bash)
  Zsh:        gmb completion zsh > "${fpath[1]}/_gmb"
  Fish:       gmb completion fish | source
  PowerShell: gmb completion powershell | Out-String | Invoke-Expression


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for completion


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--color\fP="auto"
	Color output mode: auto|always|never

.PP
\fB-c\fP, \fB--config\fP=""
	Config file path (default is $HOME/.glassmarble.yaml)

.PP
\fB--debug\fP[=false]
	Enable debug logging

.PP
\fB--dir\fP=""
	Target repository directory for analysis and queries

.PP
\fB--max-json-mb\fP=0
	Refuse to load or commit an AKG state file (akg.json) larger than this many MiB (0 = unlimited)

.PP
\fB-q\fP, \fB--quiet\fP[=false]
	Suppress non-error output

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	Verbose output logging


.SH EXAMPLE
.EX
  # Load bash completion in current session
  source <(gmb completion bash)

  # Load zsh completion in current session
  gmb completion zsh > "${fpath[1]}/_gmb"

  # Load fish completion
  gmb completion fish | source

  # Load PowerShell completion
  gmb completion powershell | Out-String | Invoke-Expression
.EE


.SH SEE ALSO
\fBgmb(1)\fP


.SH HISTORY
24-Aug-2026 Auto generated by spf13/cobra
