package compliance

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// ConfigVarRecord documents an environment variable or configuration knob.
type ConfigVarRecord struct {
	Name        string `json:"name"`
	Type        string `json:"type"`
	Default     string `json:"default"`
	Required    bool   `json:"required"`
	Deprecated  bool   `json:"deprecated"`
	Description string `json:"description"`
	SourcePath  string `json:"source_path"`
	Line        int    `json:"line"`
}

// GenerateConfigDictionary scans the codebase for environment variable and flag lookups,
// building a complete reference in docs/configuration.md.
func GenerateConfigDictionary(repoRoot string) (string, error) {
	vars, err := scanConfigVariables(repoRoot)
	if err != nil {
		return "", err
	}

	sort.Slice(vars, func(i, j int) bool {
		return vars[i].Name < vars[j].Name
	})

	var sb strings.Builder
	sb.WriteString("# Runtime Configuration & Environment Variable Dictionary\n\n")
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 18).\n")
	sb.WriteString("> Catalogs all runtime environment variables, CLI flags, and configuration parameters.\n\n")

	sb.WriteString("| Variable / Key | Type | Default | Required | Description | Source |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- | :--- | :--- |\n")

	for _, v := range vars {
		nameStr := fmt.Sprintf("`%s`", v.Name)
		if v.Deprecated {
			nameStr = fmt.Sprintf("~~`%s`~~ *(deprecated)*", v.Name)
		}

		reqStr := "Optional"
		if v.Required {
			reqStr = "**Required**"
		}

		defStr := "`-`"
		if v.Default != "" {
			defStr = fmt.Sprintf("`%s`", v.Default)
		}

		desc := v.Description
		if desc == "" {
			desc = "Runtime configuration parameter"
		}
		desc = strings.ReplaceAll(desc, "|", "\\|")
		desc = strings.ReplaceAll(desc, "\n", " ")

		sb.WriteString(fmt.Sprintf("| %s | `%s` | %s | %s | %s | [%s:%d](%s#L%d) |\n",
			nameStr, v.Type, defStr, reqStr, desc, filepath.Base(v.SourcePath), v.Line, v.SourcePath, v.Line))
	}

	outPath := filepath.Join(repoRoot, "docs", "configuration.md")
	result := sb.String()
	_, err = storage.AtomicWriteFile(outPath, []byte(result))
	return result, err
}

func scanConfigVariables(repoRoot string) ([]ConfigVarRecord, error) {
	var records []ConfigVarRecord
	seen := make(map[string]bool)
	fset := token.NewFileSet()

	err := filepath.WalkDir(repoRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == ".glassmarble" || name == "vendor" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		relPath, _ := filepath.Rel(repoRoot, path)
		relPath = filepath.ToSlash(relPath)

		node, parseErr := parser.ParseFile(fset, path, nil, 0)
		if parseErr != nil {
			return nil
		}

		ast.Inspect(node, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}

			fnStr := exprToString(call.Fun)
			if fnStr == "os.Getenv" || fnStr == "os.LookupEnv" {
				if len(call.Args) > 0 {
					if lit, ok := call.Args[0].(*ast.BasicLit); ok {
						val := strings.Trim(lit.Value, `"`)
						if val != "" && !seen[val] {
							seen[val] = true
							pos := fset.Position(call.Pos())
							records = append(records, ConfigVarRecord{
								Name:        val,
								Type:        "string",
								Default:     "",
								Required:    false,
								Deprecated:  strings.Contains(strings.ToLower(val), "legacy") || strings.Contains(strings.ToLower(val), "old"),
								Description: fmt.Sprintf("Environment variable read via %s", fnStr),
								SourcePath:  relPath,
								Line:        pos.Line,
							})
						}
					}
				}
			}

			return true
		})

		return nil
	})

	return records, err
}
