package compliance

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// DependencyRecord documents an external dependency and its license risk.
type DependencyRecord struct {
	Module      string `json:"module"`
	Version     string `json:"version"`
	Indirect    bool   `json:"indirect"`
	LicenseSPDX string `json:"license_spdx"`
	RiskLevel   string `json:"risk_level"` // Low, Medium, High (Copyleft)
}

// GenerateSBOM parses manifest files (go.mod) to build a software bill of materials
// and license compliance audit at docs/compliance/dependencies.md.
func GenerateSBOM(repoRoot string) (string, error) {
	deps, err := parseGoModDependencies(repoRoot)
	if err != nil {
		return "", err
	}

	sort.Slice(deps, func(i, j int) bool {
		if deps[i].Indirect == deps[j].Indirect {
			return deps[i].Module < deps[j].Module
		}
		return !deps[i].Indirect
	})

	var sb strings.Builder
	sb.WriteString("# Software Bill of Materials (SBOM) & License Risk Analysis\n\n")
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 25).\n")
	sb.WriteString("> Evaluates third-party software dependencies, versions, and license compliance risks.\n\n")

	// Section 1: License Risk Matrix
	highRiskCount := 0
	directCount := 0
	for _, d := range deps {
		if !d.Indirect {
			directCount++
		}
		if d.RiskLevel == "High" {
			highRiskCount++
		}
	}

	sb.WriteString("## Compliance Executive Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Total Dependencies:** %d (%d direct, %d indirect)\n", len(deps), directCount, len(deps)-directCount))
	sb.WriteString(fmt.Sprintf("- **Copyleft / High Risk Dependencies:** %d\n", highRiskCount))
	sb.WriteString(fmt.Sprintf("- **Permissive Dependencies (MIT / Apache / BSD):** %d\n\n", len(deps)-highRiskCount))

	sb.WriteString("## Dependency Inventory\n\n")
	sb.WriteString("| Module / Package | Version | Type | License | Risk Profile |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- | :--- |\n")

	for _, d := range deps {
		typeStr := "Direct"
		if d.Indirect {
			typeStr = "Indirect"
		}

		riskBadge := "🟢 Low"
		if d.RiskLevel == "High" {
			riskBadge = "🔴 High (Copyleft)"
		} else if d.RiskLevel == "Medium" {
			riskBadge = "🟡 Medium"
		}

		sb.WriteString(fmt.Sprintf("| **`%s`** | `%s` | %s | `%s` | %s |\n",
			d.Module, d.Version, typeStr, d.LicenseSPDX, riskBadge))
	}

	outPath := filepath.Join(repoRoot, "docs", "compliance", "dependencies.md")
	result := sb.String()
	_, err = storage.AtomicWriteFile(outPath, []byte(result))
	return result, err
}

func parseGoModDependencies(repoRoot string) ([]DependencyRecord, error) {
	modPath := filepath.Join(repoRoot, "go.mod")
	file, err := os.Open(modPath)
	if err != nil {
		return nil, fmt.Errorf("reading go.mod: %w", err)
	}
	defer file.Close()

	var deps []DependencyRecord
	scanner := bufio.NewScanner(file)
	inRequire := false

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "require (") {
			inRequire = true
			continue
		}
		if inRequire && line == ")" {
			inRequire = false
			continue
		}

		if inRequire || strings.HasPrefix(line, "require ") {
			line = strings.TrimPrefix(line, "require ")
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				mod := parts[0]
				ver := parts[1]
				indirect := strings.Contains(line, "// indirect")

				spdx := "MIT"
				risk := "Low"
				lower := strings.ToLower(mod)
				if strings.Contains(lower, "gpl") || strings.Contains(lower, "agpl") {
					spdx = "GPL-3.0"
					risk = "High"
				} else if strings.Contains(lower, "apache") {
					spdx = "Apache-2.0"
				} else if strings.Contains(lower, "bsd") {
					spdx = "BSD-3-Clause"
				}

				deps = append(deps, DependencyRecord{
					Module:      mod,
					Version:     ver,
					Indirect:    indirect,
					LicenseSPDX: spdx,
					RiskLevel:   risk,
				})
			}
		}
	}

	return deps, scanner.Err()
}
