package compliance

import (
	"bufio"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// DependencyRecord documents an external dependency and its license risk.
type DependencyRecord struct {
	Module      string `json:"module"`
	Version     string `json:"version"`
	Indirect    bool   `json:"indirect"`
	LicenseSPDX string `json:"license_spdx"`
	RiskLevel   string `json:"risk_level"` // Low, Medium, High (Copyleft)
}

// GenerateSBOM parses manifest files (go.mod, package.json, Cargo.toml) to build
// a software bill of materials and license compliance audit at docs/compliance/dependencies.md.
func GenerateSBOM(repoRoot string) (string, error) {
	deps, err := parseGoModDependencies(repoRoot)
	if err != nil {
		return "", err
	}
	deps = append(deps, parsePackageJSONDependencies(repoRoot)...)
	deps = append(deps, parseCargoDependencies(repoRoot)...)

	sort.Slice(deps, func(i, j int) bool {
		if deps[i].Indirect == deps[j].Indirect {
			return deps[i].Module < deps[j].Module
		}
		return !deps[i].Indirect
	})

	var sb strings.Builder
	sb.WriteString("# Software Bill of Materials (SBOM) & License Risk Analysis\n\n")
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 25).\n")
	sb.WriteString("> Evaluates third-party software dependencies, versions, and license compliance risks.\n\n")

	// Section 1: License Risk Matrix
	highRiskCount := 0
	directCount := 0
	for _, d := range deps {
		if !d.Indirect {
			directCount++
		}
		if d.RiskLevel == "High" {
			highRiskCount++
		}
	}

	sb.WriteString("## Compliance Executive Summary\n\n")
	sb.WriteString(fmt.Sprintf("- **Total Dependencies:** %d (%d direct, %d indirect)\n", len(deps), directCount, len(deps)-directCount))
	sb.WriteString(fmt.Sprintf("- **Copyleft / High Risk Dependencies:** %d\n", highRiskCount))
	sb.WriteString(fmt.Sprintf("- **Permissive Dependencies (MIT / Apache / BSD):** %d\n\n", len(deps)-highRiskCount))

	sb.WriteString("## Dependency Inventory\n\n")
	sb.WriteString("| Module / Package | Version | Type | License | Risk Profile |\n")
	sb.WriteString("| :--- | :--- | :--- | :--- | :--- |\n")

	for _, d := range deps {
		typeStr := "Direct"
		if d.Indirect {
			typeStr = "Indirect"
		}

		riskBadge := "🟢 Low"
		if d.RiskLevel == "High" {
			riskBadge = "🔴 High (Copyleft)"
		} else if d.RiskLevel == "Medium" {
			riskBadge = "🟡 Medium"
		}

		sb.WriteString(fmt.Sprintf("| **`%s`** | `%s` | %s | `%s` | %s |\n",
			d.Module, d.Version, typeStr, d.LicenseSPDX, riskBadge))
	}

	outPath := filepath.Join(repoRoot, "docs", "compliance", "dependencies.md")
	result := sb.String()
	_, err = storage.AtomicWriteFile(outPath, []byte(result))
	return result, err
}

func parseGoModDependencies(repoRoot string) ([]DependencyRecord, error) {
	modPath := filepath.Join(repoRoot, "go.mod")
	file, err := os.Open(modPath)
	if err != nil {
		return nil, fmt.Errorf("reading go.mod: %w", err)
	}
	defer file.Close()

	var deps []DependencyRecord
	scanner := bufio.NewScanner(file)
	inRequire := false

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "require (") {
			inRequire = true
			continue
		}
		if inRequire && line == ")" {
			inRequire = false
			continue
		}

		if inRequire || strings.HasPrefix(line, "require ") {
			line = strings.TrimPrefix(line, "require ")
			parts := strings.Fields(line)
			if len(parts) >= 2 {
				mod := parts[0]
				ver := parts[1]
				indirect := strings.Contains(line, "// indirect")

				spdx, risk := classifyLicense(mod)

				deps = append(deps, DependencyRecord{
					Module:      mod,
					Version:     ver,
					Indirect:    indirect,
					LicenseSPDX: spdx,
					RiskLevel:   risk,
				})
			}
		}
	}

	return deps, scanner.Err()
}

// knownLicenses maps well-known modules to their published SPDX identifiers.
// This avoids the dangerous "default MIT" heuristic for unrecognized modules.
var knownLicenses = map[string]string{
	"github.com/spf13/cobra":             "Apache-2.0",
	"github.com/spf13/pflag":             "BSD-3-Clause",
	"github.com/spf13/viper":             "MIT",
	"github.com/stretchr/testify":        "MIT",
	"gopkg.in/yaml.v3":                   "MIT",
	"gopkg.in/yaml.v2":                   "Apache-2.0",
	"github.com/charmbracelet/bubbletea": "MIT",
	"github.com/charmbracelet/lipgloss":  "MIT",
	"github.com/charmbracelet/bubbles":   "MIT",
	"golang.org/x/sync":                  "BSD-3-Clause",
	"golang.org/x/mod":                   "BSD-3-Clause",
	"golang.org/x/tools":                 "BSD-3-Clause",
	"github.com/google/go-cmp":           "BSD-3-Clause",
	"github.com/google/uuid":             "BSD-3-Clause",
	"go.uber.org/zap":                    "MIT",
	"github.com/sirupsen/logrus":         "MIT",
	"github.com/mattn/go-sqlite3":        "MIT",
	"github.com/lib/pq":                  "MIT",
}

// classifyLicense returns the SPDX identifier and risk level for a module.
// Unknown modules return "Unknown" / "Medium" so they surface for manual
// review instead of being silently marked permissive.
func classifyLicense(mod string) (spdx, risk string) {
	lower := strings.ToLower(mod)
	switch {
	case strings.Contains(lower, "agpl"):
		return "AGPL-3.0", "High"
	case strings.Contains(lower, "gpl"):
		return "GPL-3.0", "High"
	case strings.Contains(lower, "lgpl"):
		return "LGPL-3.0", "High"
	case strings.Contains(lower, "mpl"):
		return "MPL-2.0", "Medium"
	case strings.Contains(lower, "epl"):
		return "EPL-2.0", "Medium"
	case strings.Contains(lower, "apache"):
		return "Apache-2.0", "Low"
	case strings.Contains(lower, "bsd"):
		return "BSD-3-Clause", "Low"
	case strings.Contains(lower, "mit"):
		return "MIT", "Low"
	}
	if spdx, ok := knownLicenses[mod]; ok {
		return spdx, "Low"
	}
	return "Unknown (manual review)", "Medium"
}

// parsePackageJSONDependencies extracts npm dependencies (Pillar 25 polyglot).
func parsePackageJSONDependencies(repoRoot string) []DependencyRecord {
	data, err := os.ReadFile(filepath.Join(repoRoot, "package.json"))
	if err != nil {
		return nil
	}
	var pkg struct {
		Dependencies    map[string]string `json:"dependencies"`
		DevDependencies map[string]string `json:"devDependencies"`
	}
	if err := json.Unmarshal(data, &pkg); err != nil {
		return nil
	}
	var deps []DependencyRecord
	for mod, ver := range pkg.Dependencies {
		spdx, risk := classifyLicense(mod)
		deps = append(deps, DependencyRecord{Module: "npm:" + mod, Version: ver, LicenseSPDX: spdx, RiskLevel: risk})
	}
	for mod, ver := range pkg.DevDependencies {
		spdx, risk := classifyLicense(mod)
		deps = append(deps, DependencyRecord{Module: "npm:" + mod + " (dev)", Version: ver, LicenseSPDX: spdx, RiskLevel: risk})
	}
	return deps
}

// parseCargoDependencies extracts Rust crate dependencies (Pillar 25 polyglot).
func parseCargoDependencies(repoRoot string) []DependencyRecord {
	file, err := os.Open(filepath.Join(repoRoot, "Cargo.toml"))
	if err != nil {
		return nil
	}
	defer file.Close()
	var deps []DependencyRecord
	inDeps := false
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "[") {
			inDeps = strings.HasPrefix(line, "[dependencies")
			continue
		}
		if inDeps && strings.Contains(line, "=") {
			parts := strings.SplitN(line, "=", 2)
			mod := strings.TrimSpace(parts[0])
			ver := strings.Trim(strings.TrimSpace(parts[1]), `"`)
			if mod != "" {
				spdx, risk := classifyLicense(mod)
				deps = append(deps, DependencyRecord{Module: "crate:" + mod, Version: ver, LicenseSPDX: spdx, RiskLevel: risk})
			}
		}
	}
	return deps
}
