// Package compliance implements Phase 6 Enterprise & Compliance pillars:
// - Pillar 17: Security & Compliance Threat Model Doc
// - Pillar 18: Configuration & Environment Variable Dictionary
// - Pillar 25: Dependency, SBOM & License Risk Docs
// - Pillar 34: API Surface Boundary & Visibility Enforcement
package compliance

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"path/filepath"
	"sort"
	"strings"

	"github.com/Syamchand123/GlassMarble/internal/doc_engine/storage"
)

// SecurityItem represents a security-relevant code element detected by the engine.
type SecurityItem struct {
	Category    string // Ingress, Egress, Crypto, SecretEnv
	Name        string
	Description string
	SourcePath  string
	Line        int
}

// GenerateThreatModel statically inspects entry points, network calls, crypto usage,
// and secret variables to produce docs/security/threat_model.md.
func GenerateThreatModel(repoRoot string) (string, error) {
	items, err := scanSecurityElements(repoRoot)
	if err != nil {
		return "", err
	}

	sort.Slice(items, func(i, j int) bool {
		if items[i].Category == items[j].Category {
			return items[i].Name < items[j].Name
		}
		return items[i].Category < items[j].Category
	})

	var sb strings.Builder
	sb.WriteString("# System Threat Model & Security Architecture\n\n")
	sb.WriteString("> Auto-generated by GlassMarble Documentation Intelligence Engine (Pillar 17).\n")
	sb.WriteString("> Maps trust boundaries, ingress entry points, egress integrations, and cryptographic primitives.\n\n")

	byCat := make(map[string][]SecurityItem)
	for _, item := range items {
		byCat[item.Category] = append(byCat[item.Category], item)
	}

	categories := []struct {
		Key   string
		Title string
		Desc  string
	}{
		{"Ingress", "1. Ingress Boundaries & Public Entry Points", "Network entry points, HTTP handlers, CLI commands, and IPC interfaces that receive untrusted input."},
		{"Egress", "2. Egress Calls & Outbound Dependencies", "External service calls, cloud APIs, database connectors, and upstream protocols."},
		{"Crypto", "3. Cryptographic Primitives & Key Management", "Encryption, hashing, TLS configurations, and HMAC/token signing mechanisms."},
		{"SecretEnv", "4. Secret Environment Variables & Credential Ingestion", "Environment variables ingesting API keys, tokens, passwords, and private credentials."},
	}

	for _, cat := range categories {
		sb.WriteString(fmt.Sprintf("## %s\n\n", cat.Title))
		sb.WriteString(fmt.Sprintf("> %s\n\n", cat.Desc))

		list := byCat[cat.Key]
		if len(list) == 0 {
			sb.WriteString("No explicit elements detected in this category.\n\n")
			continue
		}

		sb.WriteString("| Component / Identifier | Description / Role | Source Location |\n")
		sb.WriteString("| :--- | :--- | :--- |\n")
		for _, el := range list {
			sb.WriteString(fmt.Sprintf("| **`%s`** | %s | [%s:%d](%s#L%d) |\n",
				el.Name, el.Description, filepath.Base(el.SourcePath), el.Line, el.SourcePath, el.Line))
		}
		sb.WriteString("\n")
	}

	outPath := filepath.Join(repoRoot, "docs", "security", "threat_model.md")
	result := sb.String()
	_, err = storage.AtomicWriteFile(outPath, []byte(result))
	return result, err
}

func scanSecurityElements(repoRoot string) ([]SecurityItem, error) {
	var items []SecurityItem
	fset := token.NewFileSet()

	err := filepath.WalkDir(repoRoot, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return nil
		}
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == ".glassmarble" || name == "vendor" || name == "node_modules" {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}

		relPath, _ := filepath.Rel(repoRoot, path)
		relPath = filepath.ToSlash(relPath)

		node, parseErr := parser.ParseFile(fset, path, nil, 0)
		if parseErr != nil {
			return nil
		}

		ast.Inspect(node, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}

			fnStr := exprToString(call.Fun)
			pos := fset.Position(call.Pos())

			// 1. Ingress
			if strings.Contains(fnStr, "HandleFunc") || strings.Contains(fnStr, "Handle") || strings.Contains(fnStr, "AddCommand") {
				items = append(items, SecurityItem{
					Category:    "Ingress",
					Name:        fnStr,
					Description: "Public ingress handler or CLI command registration",
					SourcePath:  relPath,
					Line:        pos.Line,
				})
			}

			// 2. Egress
			if strings.Contains(fnStr, "http.Get") || strings.Contains(fnStr, "http.Post") || strings.Contains(fnStr, "sql.Open") || strings.Contains(fnStr, "grpc.Dial") {
				items = append(items, SecurityItem{
					Category:    "Egress",
					Name:        fnStr,
					Description: "Outbound egress connection to database or external network service",
					SourcePath:  relPath,
					Line:        pos.Line,
				})
			}

			// 3. Crypto
			if strings.Contains(fnStr, "sha256.") || strings.Contains(fnStr, "aes.") || strings.Contains(fnStr, "tls.") || strings.Contains(fnStr, "hmac.") {
				items = append(items, SecurityItem{
					Category:    "Crypto",
					Name:        fnStr,
					Description: "Cryptographic cipher, hashing, or secure protocol primitive",
					SourcePath:  relPath,
					Line:        pos.Line,
				})
			}

			// 4. SecretEnv
			if fnStr == "os.Getenv" || fnStr == "os.LookupEnv" {
				if len(call.Args) > 0 {
					if lit, ok := call.Args[0].(*ast.BasicLit); ok {
						val := strings.Trim(lit.Value, `"`)
						lower := strings.ToLower(val)
						if strings.Contains(lower, "key") || strings.Contains(lower, "secret") || strings.Contains(lower, "token") || strings.Contains(lower, "password") {
							items = append(items, SecurityItem{
								Category:    "SecretEnv",
								Name:        val,
								Description: "Sensitive credential ingested from runtime environment variable",
								SourcePath:  relPath,
								Line:        pos.Line,
							})
						}
					}
				}
			}

			return true
		})

		return nil
	})

	return items, err
}

func exprToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return exprToString(t.X) + "." + t.Sel.Name
	default:
		return ""
	}
}
